### PR TITLE
Add option to retype the passcode

### LINKED ISSUE #1496: If password in enroll link is incorrect, user should have a chance to put in the correct one
For edit-a-thons and other events, an enroll link may get distributed before the passcode is changed (or it may be miscopied). Handling incorrect passcodes silently, and prompting the user for the correct one, would be a nice improvement.

### PR DESCRIPTION
**Pull request by AmitJoki**
Fixes #1496 

image

### CODE REVIEW

**Comment by psinghal20** [comment]
@AmitJoki Maybe you can add a separate feature spec example for this feature than changing the previous one.
- Checks that user is allowed to enter the passcode again, after one failed attempt which you can do in the existing example.
- Checks that if the passcode is invalid even the second time, then display the corresponding error message.

**Comment by AmitJoki** [comment]
@ragesoss I tried working on the spec but couldn't quite set up the environment. Can you please give me some pointers as to creating a course, logging the user in as a student? I have worked out the other parts.

**Comment by ragesoss** [comment]
Check out `spec/features/student_role_spec.rb`, which includes a spec for putting in an incorrect passcode. You should be able to just extend that spec to include retyping.

**Comment by AmitJoki** [comment]
@ragesoss can you please checkout my code for spec testing. I am not able to ascertain what's wrong as PhantomJS is crashing every time for me in here.

**Pull request merged**
