### PR TITLE
Added tests for article_details reducer and user_profile component

### PR DESCRIPTION
**Pull request by airum82**
We have not changed any existing code, only added tests that were not present before.

Other contributors: Tory Dannenberg: @tdberg21, David Starr Dunn: @dsdunn
```import article_details from '../../app/assets/javascripts/reducers/article_details';
import { RECEIVE_ARTICLE_DETAILS } from "../../app/assets/javascripts/constants/article_details";
import '../testHelper';

describe('article_details reducer', () => {

  it('Should return initial state if no action type matches', () => {
    const mockAction = {
      type: 'NO_TYPE'
    };
    const initialState = {};

    const result = article_details(undefined, mockAction);
    expect(result).to.deep.eq(initialState);
  });

  it('should reutrn a new state if action type is RECEIVE_ARTICLE_DETAILS', () => {
    const mockAction = {
      type: RECEIVE_ARTICLE_DETAILS,
      articleId: 586,
      data: {
        article_details: 'best article ever'
      }
    };
    const expectedState = {
      586: 'best article ever'
    };
    expect(article_details(undefined, mockAction)).to.deep.eq(expectedState);
  });
});
```
```
import React from 'react';
import { shallow } from 'enzyme';
import '../../testHelper';
import UserUploads from '../../../app/assets/javascripts/components/user_profiles/user_uploads.jsx';

describe('UserUploads', () => {
  it('should not render the upload list if there are no user uploads', () => {
    const mockUploads = [];
    const wrapper = shallow(<UserUploads uploads={mockUploads} />);
    expect(wrapper.find('UploadList').length).to.equal(0);
  });

  it('should render the upload list component if there are user uploads', () => {
    const mockUploads = [{ id: 1 }, { id: 2 }];
    const wrapper = shallow(<UserUploads uploads={mockUploads} />);
    expect(wrapper.find('UploadList').length).to.equal(1);
  });
});

```
```PASS  test/components/user_profiles/user_uploads.spec.jsx (9.285s)
  UserUploads
    ✓ should not render the upload list if there are no user uploads (11ms)
    ✓ should render the upload list component if there are user uploads (2ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        10.266s
```

### CODE REVIEW

**Comment by ragesoss** [comment]
Hi! It looks like a change to schema.rb snuck into the PR unintentionally. Please remove that.

There is also a linting error in one of the new specs, which is causing the test suite to fail. You should be able to see any javascript linting errors whenever you run `gulp` locally.

**Comment by airum82** [comment]
I have fixed the linting error, We did not touch the db directory at all so not sure how that got in there. Is it okay if we just delete the schema.rb file from our pr?

**Comment by ragesoss** [comment]
@airum82 the schema.rb happened when you ran the migrations to set the app up, and then they were accidentally included in the first commit (for example, if you did `git commit -a`).

You can either manually recreate the tests in new commits on a clean branch, or add a commit that reverts schema.rb to the original version.

**Comment by ragesoss** [comment]
@airum82 to clarify, the problem isn't directly about running the migrations or rolling them back. Whenever you run a migration task, schema.rb gets regenerated based on your local environment, which can include things like MySQL settings that are different from whatever was previously used to create the latest schema.rb.

Since you aren't maknig any database-related changes, the the way to revert that change will be to just copy the schema.rb from master and save that.

**Comment by airum82** [comment]
@ragesoss I have fixed the schema.rb discrepancy. Thank you for your patience.

**Comment by ragesoss** [comment]
Thanks folks! I've squashed and merged it.

**Comment by airum82** [comment]
Great! thank you for the opportunity to contribute

**Pull request merged**
