### PR TITLE
Replace jquery with vanilla JS in nav.jsx

### LINKED ISSUE #3675: replace jquery with vanilla JS in `nav.jsx`
The navbar component, `nav.jsx`, uses global jquery (`$`) to extract data from the hmtl and to find the window dimensions. These things can and should be done with vanilla JavaScript instead, as part of the gradual effort to remove the need for jquery in the codebase.

### PR DESCRIPTION
**Pull request by soumyaa1804**
## What this PR does
Fixes #3675 

## Screenshots
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3754 
## Open questions and concerns
To make it work locally on my system my local repository changes (creating package-lock.json and some changes to schema.rb) which will be unrelated to the future PRs. Can you please suggest a way so that it runs on my system as well as commit only necessary changes to PRs?

### CODE REVIEW

**Comment by ragesoss** [comment]
@soumyaa1804 I think those other changes can just be discarded on your system. Now that you've already run the database migrations, the schema.rb change shouldn't be consequential. For package-lock.json, I'm not sure what program put that in place for you, but `yarn` should be able to handle all the JS dependencies without needing that file.

**Comment by soumyaa1804** [comment]
@ragesoss Can you please help me with the error?

**Comment by soumyaa1804** [comment]
> @soumyaa1804 I think those other changes can just be discarded on your system. Now that you've already run the database migrations, the schema.rb change shouldn't be consequential. For package-lock.json, I'm not sure what program put that in place for you, but `yarn` should be able to handle all the JS dependencies without needing that file.

Yeah! I removed those files and tried to set it up again and it worked!
Can you please help me with the travis checks? Is it because of the dummy article names I added while exploring the app on my local machine?

**Comment by soumyaa1804** [comment]
The check shows the error on the server-side:
```
Failures:
  1) Student users visiting the ?enroll=passcode url works even if a student has never logged in before
     Failure/Error: expect(find('tbody', match: :first)).to have_content 'Ragesoss'
     Capybara::ElementNotFound:
       Unable to find visible css "tbody"
     # ./spec/features/student_role_spec.rb:235:in `block (3 levels) in <top (required)>'
```
```
Failures:
  1) ArticleStatusManager.update_article_status_for_course marks deleted articles as "deleted"
     Failure/Error: expect(Article.find(1).deleted).to be true
       expected true
            got false
     # ./spec/lib/article_status_manager_spec.rb:32:in `block (4 levels) in <top (required)>'
     # ./spec/lib/article_status_manager_spec.rb:23:in `block (3 levels) in <top (required)>'
```
Can you please suggest what could be done to fix this?

**Comment by ragesoss** [comment]
Looks like those errors from earlier might have just been flaky tests.

**Pull request merged**
