### PR TITLE
Training: Misc changes in frontend

### PR DESCRIPTION
**Pull request by AbdealiJK**
Fixes https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/567

### CODE REVIEW

**Comment by ragesoss** [comment]
@AbdealiJK thanks much! Our design lead is going to check this over soon. He took a quick look today, and it looks like we'll need to add some more specific css so that these changes don't also affect the training module pages. See the new screenshots in #567, which show unintended side effects.

**Comment by ragesoss** [comment]
@AbdealiJK just a poke; if you're still interested, an update that separates the side effects would make this ready to merge.

**Comment by AbdealiJK** [comment]
@ragesoss I haven't gotten about to doing it yet. If someone else wishes to complete it, they can

**Comment by ragesoss** [comment]
Thanks again, @AbdealiJK! I finally got around to tweaking your patch to remove the side effects: c0299399d9badf10fed36651f9fe614d1dfdaae7

**Pull request closed without merging**
