### PR TITLE
Detect locale from Accept-Language header

### PR DESCRIPTION
**Pull request by adamwight**
Bug: T89008

### CODE REVIEW

**Comment by ragesoss** [comment]
@adamwight thanks! No sure why the build doesn't run for this PR (issue #447), but locally I get this broken spec:

```
  1) the home page non-default locales should switch languages
     Failure/Error: expect(page.find('header')).to have_content 'Long label for the number'
       expected to find text "Long label for the number" in "Wiki Ed Dashboard 10 Wiki Ed Courses 10 Students 10 have completed training 0 Chars Added 0 Article Views 10 Articles Edited 0 Articles Created"
     # ./spec/features/home_page_spec.rb:183:in `block (3 levels) in <top (required)>'
```

**Comment by adamwight** [comment]
Okay, that shouldn't be difficult to fix.  I'll try to beef up the locale tests while I'm in there.

**Comment by adamwight** [comment]
Oops!  Rebased out of bad habit.

**Comment by ragesoss** [comment]
LGTM!

**Pull request merged**
