### PR TITLE
Refactor componentWillMount and componentWillReceiveProps

### LINKED ISSUE #3478: Refactor componentWillMount and componentWillReceiveProps
### What is happening?

componentWillMount and componentWillReceiveProps were producing warnings in the browser console, saying that use of the soon-to-be-depricated componentWillMount and componentWillReceiveProps has to be refactored and phased out. 

Commit [a0321daf12d62479d84eff5729dafce4089111bf](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3472/commits/a0321daf12d62479d84eff5729dafce4089111bf)
in PR #3472 renames these methods to the supported UNSAFE_ versions. 34 occurrences were replaced. 
 
The next step is to refactor these methods. 

### To Reproduce

1. Open dev code of project
2. Search whole project for UNSAFE_
3. See the React methods labeled UNSAFE_

### Expected behavior
A full refactor of the UNSAFE_ methods in accordance with the new React documentation.

### System Information

 - OS: MAC OS High Sierra Version 10.13.6
 - Browser Chrome Version 78.0.3904.70

### Additional context
From comment in PR #3472 
(This PR doesn't solve the issue, the conversation here explains the context)

> Hey @khyatisoneji, thanks for looking it over. I did notice the pre-existing warnings. Here is what I found. I am opening a separate issue to track that work: 
> 
> I looked at the errors and the React documentation. I tried changing `componentWillReceiveProps` in `app/assets/javascripts/components/revisions/diff-viewer.jsx` to `componentDidUpdate` and I am left with diffs that won't load. I tried the same for `app/assets/javascripts/components/common/article-viewer.jsx` with the same result.
> 
> I think that properly updating all the soon-to-be-deprecated `componentWillMount` and `componentWillReceiveProps` methods is going to be a separate refactoring using the new React version way of doing things. 
> 
> In the meantime, I ran this command from the documentation to rename such methods in `app/assets/javascripts`:
> 
> `npx react-codemod rename-unsafe-lifecycles` 
> 
> `componentWillReceiveProps()` -> `UNSAFE_componentWillReceiveProps()`
> `componentWillMount()` -> `UNSAFE_componentWillMount()`
> 
> 34 changes were made.
> 
> From [React Blog: Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
> 
> > **Gradual Migration Path**
> > 
> > React follows semantic versioning, so this change will be gradual. Our current plan is:
> > 
> > **16.3:** Introduce aliases for the unsafe lifecycles, UNSAFE_componentWillMount, UNSAFE_componentWillReceiveProps, and UNSAFE_componentWillUpdate. (Both the old lifecycle names and the new aliases will work in this release.)
> > 
> > **A future 16.x release:** Enable deprecation warning for componentWillMount, componentWillReceiveProps, and componentWillUpdate. (Both the old lifecycle names and the new aliases will work in this release, but the old names will log a DEV-mode warning.)
> > 
> > **17.0:** Remove componentWillMount, componentWillReceiveProps, and componentWillUpdate . (Only the new “UNSAFE_” lifecycle names will work from this point forward.)
> >

### PR DESCRIPTION
**Pull request by ihsavru**
fix #3478 
Refactored following files:
- upload.jsx
- upload_viewer.jsx
- uploads_handler.jsx

### CODE REVIEW

**Comment by ragesoss** [comment]
Looks like the feature spec that failed is related to the uploads view. Does that spec pass locally for you?

**Comment by ihsavru** [comment]
@ragesoss for some reason all of the specs fail locally for me. I made some changes in the code, used `getDerivedStateFromProps` instead of `componentDidUpdate` and the build passes now.

**Comment by ragesoss** [comment]
It looks like this breaks UploadViewer. When I click a thumbnail in the Uploads, I get a `this is undefined` error from isUploadViewerOpen in upload.jsx, and the viewer doesn't open.

(I'll open an issue for adding a browser test for using the upload viewer, as this kind of thing should have broken the build.)

**Comment by ihsavru** [comment]
Sorry I missed out on that, I forgot to bind `this` to the functions that's why it was showing undefined. I'll try adding specs for this.

**Comment by ragesoss** [comment]
This looks good to me, and everything seems to work the same way as before. I did notice another-already present problem with unnecessary requests when there are multiple pages of images, which I'll file a new issue for.

**Pull request merged**
