### PR TITLE
Add Course subtypes using Single Table Inheritance

### PR DESCRIPTION
**Pull request by ragesoss**
The default ClassroomProgramCourse behaves the same as Course did previously. The new VisitingScholarship and Editathon course types have wiki edits disabled.

@thenickcox Please review this. :-)

### CODE REVIEW

**Comment by thenickcox** [comment]
@ragesoss In general, this looks nice and simple. A few questions: How does the course type get set? Also, I'd love to see `Course` validate `type` on [the inclusion in](http://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_inclusion_of) an array of accepted `Course` types to add some documentation as to what the possible values for `type` are, and get the benefit of ensuring good data.

**Comment by ragesoss** [comment]
@thenickcox 

* *How does course type get set?* For now, manually. The next step would be to add a selector in Course Details that only shows up for admins, to choose among the valid types.

* Validation: done.

**Comment by thenickcox** [comment]
@ragesoss Test for the validation?

**Comment by ragesoss** [comment]
@thenickcox done.

**Comment by ragesoss** [comment]
@thenickcox if you're happy with it now, I'll merge it and push it to staging.

**Comment by thenickcox** [comment]
LGTM :+1:

**Pull request merged**
