### PR TITLE
Add category search under advanced options in article_finder

### LINKED ISSUE #1983: Hide filters and category search feature under advanced search settings in article finder
Search filters and category search options in article finder are suitable for advanced users and can be hidden under advanced search options to simplify the UI.

### PR DESCRIPTION
**Pull request by khyatisoneji**
Fix #1983 

Screens:
screen shot 2018-09-18 at 10 27 33 pm
screen shot 2018-09-18 at 10 27 43 pm
screen shot 2018-09-18 at 10 27 49 pm

### CODE REVIEW

**Comment by psinghal20** [comment]
@khyatisoneji The layout is still cluttered a little bit. You can try reducing the spacing between the `Advanced Filters` button and the filter fields.
- Try increasing spacing between the fields a little more.
- Vertically align the filter fields
- Increase the vertical spacing between the search bar and filter fields.

**Comment by khyatisoneji** [comment]
New screen looks like:

screen shot 2018-09-19 at 11 14 45 am

Please have a look @psinghal20

**Comment by psinghal20** [comment]
Looks good to me! @ragesoss can you take a final look and merge?

**Comment by ragesoss** [comment]
This looks good. Just a few language tweaks:

* Instead of adding new interface messages, we should just change the existing ones. This will result in less wasted work by translators, and avoid having people add new translations for messages that are no longer used. In particular, 'Show Filters' could become just 'Show Options', and 'Hide Filters' could become 'Hide Options'.

Also, I think we should change the tagline beneath the title to "Let's find a Wikipedia article to work on."

It will make sense at some point to add more guidance on the recommended way to use the tool and interpret the results, but for now that will be an decent improvement.

**Comment by khyatisoneji** [comment]
@ragesoss Done.

screen shot 2018-09-19 at 10 26 32 pm

**Pull request merged**
