### PR TITLE
added URL feedback on filter change

### PR DESCRIPTION
**Pull request by TheTrio**
## What this PR does

Addresses #4685. It introduces 3 new search query params. 

| Key | Possible Values | Default |
| --------------- | --------------- | --------------- |
| wiki | `all` and other wikis(like `en.wikipedia`) | `all` |
| tracked | `tracked`, `untracked` and `both` | `tracked` |
| newness | `new`, `existing` and  `both` | `both` |

For example, the URL for this 
image

will be `/courses/Southwestern_University/Biochemistry_(Fall)/articles/edited?newness=existing&tracked=tracked&wiki=en.wikipedia`

As the user changes the filters, the URL is updated automatically, making it easier to share specific views.
## Open questions and concerns

Currently, the filters are not rendered if there are only 1 type of edits. For example, if there exists only one wiki, or if there are no untracked edits, their respective filters are not visible.

However, the search params don't have any such restriction.If you add `&tracked=untracked` to a course without any untracked edits, it will show an empty list. Since the filters are not visible, the user won't have any way to change the filter(other than updating the URL manually of course)

I'm not sure if I should bother with this particular case, since the user will have to manually edit the URL to get an empty view in the first place.

### CODE REVIEW

**Comment by ragesoss** [comment]
Cool! This looks reasonable. I'll test it out once the build is passing.

**Comment by TheTrio** [comment]
As discussed, have deleted the test file. Will try extending the tests in `spec/features/course_page_spec.rb` to check for the search params in another PR.

**Comment by ragesoss** [comment]
This works fine, and I can merge it. One problem I noticed while testing it out is that filter state is persisted if you navigate to a different tab and then navigate back, but when you navigate back, the filter dropdowns don't reflect the filter state; they show the default value even though the articles list is being filtered differently. I'll open a separate issue for that.

**Comment by ragesoss** [comment]
https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/4805

**Pull request merged**
