### PR TITLE
Store sum of references in courses_users

### PR DESCRIPTION
**Pull request by khyatisoneji**

### CODE REVIEW

**Comment by khyatisoneji** [comment]
The tests are breaking as this requires the features_previous PR to be merged. Please retrigger this pipeline after the PR is merged so that the breaking tests will pass

**Comment by ragesoss** [comment]
You can rebase this on your other branch.

**Comment by khyatisoneji** [comment]
I am not that good with github, so please check if this rebase is ok.

**Comment by ragesoss** [comment]
Hmm... looks like it ended up with some conflicts.

I recommend starting a new branch from the latest `master`, then use `cherry-pick` to add the courses_users changes (or just recreate the commits, as they aren't that big).

**Pull request closed without merging**
