### PR TITLE
Fixed assign button popover by wrapping the long title new line

### PR DESCRIPTION
**Pull request by sastava007**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
FIxed the popover which was going out of the screen when the title is too long by wrapping the text to a new line and limiting the max-width.

## Screenshots
Before:
https://user-images.githubusercontent.com/848483/73482531-c33aa080-4352-11ea-85fe-be1d483cf6f8.png
  ##image

After:
after

## Open questions and concerns
This PR aims to solve issue #3715 #3719 
@ragesoss please review & merge.

### CODE REVIEW

**Comment by ragesoss** [comment]
@sastava007 thanks! The wrapping behavior looks great (and thanks for the GIF, perfect!).

I think the 'Assign' button should remain in the current position, to the right of the input.

**Comment by sastava007** [comment]
> @sastava007 thanks! The wrapping behavior looks great (and thanks for the GIF, perfect!).
> 
> I think the 'Assign' button should remain in the current position, to the right of the input.

@Okay, I'll fix that button position and update.

**Comment by sastava007** [comment]
after1
@ragesoss I have fixed it, please review.

**Comment by ragesoss** [comment]
This looks good for the assign button, but that CSS looks like it might apply to many popover UI elements, not just this one. Have you looked for regressions in the styling of any of the other popover components?

**Comment by ragesoss** [comment]
Hmm... this causes a regression in the instance of the assign button used in other places, breaking the layout of the button that links to the Article Finder.

button layout

It also looks like the original bug is not longer valid, since we just deployed the change to the Students tab layout that removes the AssignButton from the Students table.

Thanks for working on this! Sorry that it ended up not being used.

**Pull request closed without merging**
