### PR TITLE
Refactored article_finder_row from class component to functional component

### PR DESCRIPTION
**Pull request by om-chauhan1**
## What this PR does
This PR converted the article_finder_row from class to functional component.
useState and useEffect hooks are used where they are required.

## Videos

For Article Finder Row
Before:
[Before.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/b84ed5ee-5066-40d6-aca5-1701bc37d3a7)

After:
[After.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/1367e45e-bcfd-4a63-8a0f-017ee1faa4cc)

Kindly review my work.

### CODE REVIEW

**Comment by om-chauhan1** [comment]
@ragesoss  Kindly send me slack invite.
My Email id - omchauhan64408@gmail.com

**Comment by om-chauhan1** [comment]
Also converted Article Finder from class component to functional component.

## Videos

For Article Finder 
Before:
[Before.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/b6214919-ad36-4f25-bcc7-84fa2b647b39)

After:
[After.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/f2954ea1-11bc-4992-bcfd-09860ec5008e)

@ragesoss Kindly review both of these commits and provide feedback accordingly.

Email for Slack Workspace - "omchauhan64408@gmail.com"

**Comment by ragesoss** [comment]
Thanks! I'd prefer separate PRs for each component, as I like to have as little to review in each PR as possible. Too many lines of JS quickly becoming overwhelming for me.

**Comment by om-chauhan1** [comment]
Sorry, for any inconvenience i rolled back second component(article_finder) to its previous state. Kindly have a look and i will remember from next time to create a separate pull request for every refactored component.
Thanks

**Comment by om-chauhan1** [comment]
@ragesoss kindly send me slack invite.
Email - omchauhan64408@gmail.com

**Comment by ragesoss** [comment]
> @ragesoss kindly send me slack invite. Email - [omchauhan64408@gmail.com](mailto:omchauhan64408@gmail.com)

Looks like you've already joined; Slack says that's an existing member.

**Pull request merged**
