### PR TITLE
filtered users in article_viewer_legend

### PR DESCRIPTION
**Pull request by BaileyMcKelway**
fixed eslint issue

NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
< describe the purpose of this pull request and note the issue it addresses >

## Screenshots
Before:
< add a screenshot of the UI before your change >

After:
< add a screenshot of the UI after your change >
## Open questions and concerns
< anything you learned that you want to share, or questions you're wondering about related to this PR >

### CODE REVIEW

**Comment by BaileyMcKelway** [comment]
Thanks for responding! Yea I think that's a good idea. 

I am newer to working on this project. How can I get the data on if a student's edits where reverted?

Below is an attached image of the article data being sent to the footer component. 

Screen Shot 2020-08-24 at 10 24 51 AM

**Comment by ragesoss** [comment]
Here's an example of an article where all of the student contributions where reverted: https://dashboard.wikiedu.org/courses/Indiana_University_of_Pennsylvania/Composition_1_(English_101)_(Fall_2019)/articles/edited?showArticle=50892528

**Comment by ragesoss** [comment]
Here's an example of an article where all of the student contributions where reverted: https://dashboard.wikiedu.org/courses/Indiana_University_of_Pennsylvania/Composition_1_(English_101)_(Fall_2019)/articles/edited?showArticle=50892528

**Comment by ragesoss** [comment]
Here's an example of an article where all of the student contributions where reverted: https://dashboard.wikiedu.org/courses/Indiana_University_of_Pennsylvania/Composition_1_(English_101)_(Fall_2019)/articles/edited?showArticle=50892528

**Comment by ragesoss** [comment]
Also, in searching for an appropriate example, my colleague found a case where the student work got turned into a redirect, which is another area for improvement that I opened a new issue for: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/4171

**Comment by BaileyMcKelway** [comment]
> Here's an example of an article where all of the student contributions where reverted: https://dashboard.wikiedu.org/courses/Indiana_University_of_Pennsylvania/Composition_1_(English_101)_(Fall_2019)/articles/edited?showArticle=50892528

This is super helpful. thank you!

> This seems correct in the sense that it removes the users from the legend, but I guess there should be some indication if the edits of a student were reverted, like a horizontal list (below Edits by:) without the colored pill of legend [Reverted edits: _User1_ _User2_ _User3_] or maybe in the same 'Edits by:' list without the coloring of legend indicating that the edits of that student were reverted ( if indicating that information is a requirement). What do you think?

With the new example article, I will be able to further look into how to implement this idea.

**Comment by BaileyMcKelway** [comment]
Before:
Screen Shot 2020-08-27 at 5 09 40 PM

After:
Screen Shot 2020-08-27 at 5 08 45 PM


The highlighting for user names in ArticleViewer is applied only if there is a change to the article's HTML. This is done in the ArticleViewer.jsx function 'highlightAuthors' and then the highlighting is applied in article_viewer_legend.jsx

**Comment by ragesoss** [comment]
The screenshot here looks good, and that's a definite improvement. I can merge it like this (once I've done a code review, which will probably be early next week), although I think there's room to improve the UI a bit further if you'd like to do so. It ought to be more explicit that the non-highlighted students aren't responsible for any of the text in the latest version. Maybe this could take the form of an info icon which shows up when one or more students is un-highlighted that, on mouseover, has an explanation of the reasons why that might be. (Either because the students' edits did not make any changes to the prose of the article that could be attributed to them, or because their changes have since been reverted.)

**Comment by BaileyMcKelway** [comment]
I think that's a good idea. However, I have tried a failed to find a way to determine if a user has had their edit reverted or if they had not made any changes.

I can look into it again but do you have any advice on getting that data?

**Comment by ragesoss** [comment]
I think what you have already implemented — figuring out whether they have any HTML attributed to them ­— is all that's needed. I'm just suggesting adding something to explain what not being highlighted means and the set of possible explanations for it... without determining which one applies.

**Comment by BaileyMcKelway** [comment]
Ah, gotcha! Sorry, I thought you meant to explain what's not being highlighted specific to the user. 

Yes, I can definitely work on that.

**Comment by ragesoss** [comment]
Thanks Bailey! Give a ping if you get stuck.

**Comment by BaileyMcKelway** [comment]
Added Hover Message

**Comment by ragesoss** [comment]
I think the usernames (either with or without coloration — ideally, without, I think) should still be shown while the authorship data is loading. Other than that, this looks great.

**Comment by BaileyMcKelway** [comment]
> I think the usernames (either with or without coloration — ideally, without, I think) should still be shown while the authorship data is loading. Other than that, this looks great.

Made the change. 

Now when the authorship data is loading the names are displayed without highlighting. Once the authorship data is loaded the appropriate names will be highlighted.

**Comment by ragesoss** [comment]
Excellent, thank you! I'm going to deploy this shortly!

**Pull request merged**
