### PR TITLE
Added test for course creator reducer

### PR DESCRIPTION
**Pull request by kagehina919**
Towards #2082.
Test added for course creator reducer.
@ragesoss please review.

### CODE REVIEW

**Comment by kagehina919** [comment]
@ragesoss the jest tests have passed including the one that I added. Some tests in `bundle exec` have failed but I am not sure why.
I am taking a look into it. 
Please let me know if there is something that I am missing.

**Comment by ragesoss** [comment]
That was a random test failure, unrelated to your work. I've restarted the test.

**Comment by kagehina919** [comment]
Some tests in `bundle exec` have failed again which seem unrelated. @ragesoss could you please take a look?

**Comment by kagehina919** [comment]
@ragesoss all tests have passed, please review.
Thanks.

**Comment by ragesoss** [comment]
Thanks!

**Pull request merged**
