### PR TITLE
Normalizes the labels of revision titles

### PR DESCRIPTION
**Pull request by AmitJoki**
## What this PR does
After consolidating the wgContentNamespaces, this PR makes sure the labels in the revisions don't have too much information in them.

## Screenshots
image

### CODE REVIEW

**Comment by ragesoss** [comment]
Thanks! One more thing, a pre-existing bug that you can probably take care of along with these changes:

If the the home wiki is wikidata (and probably any other multilingual wiki without a `language` property), then the frontend displays the title of an assigned article, etc, with an `en` prefix. For example, `en:Q42`. It shouldn't do that.

**Comment by ragesoss** [comment]
This looks good. I think some unit tests with examples of the different namespace names on different projects would be helpful.

**Comment by ragesoss** [comment]
I'm going to merge now, but please open a new PR with unit tests.

**Comment by AmitJoki** [comment]
Sure. I will after I complete the ongoing excluding articles one.

**Pull request merged**
