### PR TITLE
Plagiarism store to redux

### PR DESCRIPTION
**Pull request by alpha721**
replaced plagiarism store with reducer.

### CODE REVIEW

**Comment by alpha721** [comment]
I don' t understand the error, "Cannot find module 'reselect' from 'index.js' " . The test suite is failing because of this. Can you please take a look at this @ragesoss ?

**Comment by ragesoss** [comment]
It's a new dependency. Run 'yarn' and that error will go away.

On Jan 27, 2018 1:29 AM, "Neetu" <notifications@github.com> wrote:

I don' t understand the error, "Cannot find module 'reselect' from
'index.js' " . The test suite is failing because of this. Can you please
take a look at this @ragesoss <https://github.com/ragesoss> ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1645#issuecomment-360972610>,
or mute the thread

**Comment by alpha721** [comment]
@ragesoss it does not show any error when I test it locally, all of the specs are passing, But, a lot of them are failing in the travis-build. I don't understand why.

**Comment by ragesoss** [comment]
On first glance, I can't tell either. It looks like all the feature specs are failing. The rspec feature specs are passing for you locally as well as the javascript ones?

**Comment by alpha721** [comment]
oh sorry,  I only checked for javascript. I am running rspec now.

**Pull request closed without merging**
