### PR TITLE
Makes a popover in a modal responsive

### PR DESCRIPTION
**Pull request by codingmamakaz**
## What this PR does
Makes a popover in a modal responsive.
## Screenshots
Before:
Screen Shot 2019-10-07 at 3 44 36 PM
After:
Full screen
Screen Shot 2019-10-07 at 3 16 54 PM

Width 1270px
Screen Shot 2019-10-07 at 3 17 04 PM

Mobile
Screen Shot 2019-10-07 at 3 16 29 PM

### CODE REVIEW

**Comment by khyatisoneji** [comment]
It looks great!.  But I think you should add some padding between the textbox and button

**Comment by codingmamakaz** [comment]
Screen Shot 2019-10-08 at 7 22 13 AM
Screen Shot 2019-10-08 at 7 22 48 AM

How about this?

**Comment by ragesoss** [comment]
I'm not sure why it failed. It might have been a failure to fetch one of the dependencies; looks unrelated to your code. I've restarted the build, which will probably pass if it was just an intermittent build bug.

**Comment by codingmamakaz** [comment]
Ok. Thank you! It looks like it passed this time. Is there a way for us to restart the buid if it fails again in the future or is it for admin only?

**Comment by ragesoss** [comment]
For re-running a build without adding a new commit, it's admin-only.

**Comment by ragesoss** [comment]
This looks like a definite improvement. There are some intermediate widths where it still goes off the screen, though.

intermediate width

I think the vertical layout would work fine without being responsive; using the vertical will still look fine when the page is full-width. I recommend just using the vertical layout always.

**Comment by codingmamakaz** [comment]
@ragesoss, can you tell me at which width it goes off the screen? I can't reproduce it in my browser. Would you prefer the popover to stay vertical even when the main form goes responsive at 920px?

**Comment by ragesoss** [comment]
If it's just a little over 1270 for me, in Firefox:

over 1270

Yeah, I think just having it be vertical at all page widths would be a good solution.

**Comment by ragesoss** [comment]
@codingmamakaz are you still working on this? The styling you did is good, and I'm eager to get it merged. It just needs to be redone as universal styling instead of based on screen width, and then it will be good to go.

**Comment by Manasa2850** [comment]
@ragesoss I'll work on this. Could you let me know what exactly the issue is?

**Comment by ragesoss** [comment]
@Manasa2850 the remaining thing to do is to update the change in this PR so that instead of switching to the vertical layout (see the 1270px screenshot from the first comment) only when the screen is narrow, it should use that layout all the time.

**Pull request closed without merging**
