### PR TITLE
Restored removed self-assign articles to the pool of Available Articles

### LINKED ISSUE #5549: Restore removed self-assigned articles to the pool of available articles
### Current Behavior:
At the moment, the programs and event dashboard doesn't move self-assigned articles back to the pool of available articles when remove is selected, it deletes the article completely from the program.

### Desired Behavior:
The self-assigned articles when removed should return to the list of available articles it should not be deleted from the program entirely. 

### Additional context:
1. Self-Assigned Article

Screenshot (70)

2. After selecting remove 

Screenshot (71)

3. Article not in the list of the available articles
Screenshot (72)

### PR DESCRIPTION
**Pull request by omChauhanDev**
## What this PR does
Fixes #5549 
This pr helps in restoring the un-assigned article back to the pool of available articles.

Created action to unclaim the assignment.
Created controller and its route in backend.

## Videos
Before:

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/fa84e3b5-5e9d-4329-a49d-9412e3a68f09

After:

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/4ea3dd52-8518-4a51-8460-4cb80843a51d

### CODE REVIEW

**Comment by ragesoss** [comment]
@om-chauhan1 thanks! can you resolve the merge conflict?

**Comment by om-chauhan1** [comment]
@ragesoss i have resolved that merge conflict.

**Comment by om-chauhan1** [comment]
Failed test is passing locally.

image

**Comment by om-chauhan1** [comment]
@ragesoss Sir, kindly review this.

**Comment by ragesoss** [comment]
Sorry that it's taken me so long to have a look at this.

I took a look through the code and realized that there are some important details missing from the issue description. I'll add a comment on the issue to explain.

**Pull request closed without merging**
