### PR TITLE
Added area-label to Button without text to make it readable by screen readers

### LINKED ISSUE #2531: Label remove button for students
image

The remove button (-) for students is unlabeled and therefore inaccessible by screen readers. Look for `removeButton` in AssignButton, EnrollButton, TagEditable, and CampaignEditable and add functionality so that these buttons describe what they do.

### PR DESCRIPTION
**Pull request by kunalthedev**
## What this PR does
Fixes #2531

So, from a [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) doc i found that button label can be accessed via screenreader using `area-label` attribute of button.

### CODE REVIEW

**Comment by ragesoss** [comment]
The idea behind this issue is not to change the visual UI, but instead to add a label so that the button is accessible via screen reader.

**Comment by kunalthedev** [comment]
> The idea behind this issue is not to change the visual UI, but instead to add a label so that the button is accessible via screen reader.

Ohh so you mean to add area-label attribute? ?

**Comment by ragesoss** [comment]
Something like that.

**Comment by kunalthedev** [comment]
> Per discussion, the visual UI should not be changed.

Yes I'll update it soon

**Pull request merged**
