### PR TITLE
Validate wiki

### PR DESCRIPTION
**Pull request by hin101**
Closes Waffle #1184 

Also cleaned up spec/models/wiki_spec.rb to comply with rubocop.

### CODE REVIEW

**Comment by ragesoss** [comment]
Please squash this to a single commit, to avoid adding all the merges to the history.

**Comment by ragesoss** [comment]
Unfortunately, this wreaks havoc with the test suite because it adds an external web request to many tests.

I'm not sure what the best way to handle this is. I guess one way would be to stub all of the needed requests from the spec_helper.

To do that, basically we'd edit request_helpers to add a method like `stub_wiki_validations`, and then put multiple stub requests for all the wikis that are causing problems in the test suite.

I'll take a pass at that.

**Comment by ragesoss** [comment]
The test side of this is way trickier than I had anticipated. I have one possible approach here: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/101a47b9020ef2548fd2c0411f8c354df483a635

I'd love to get some other opinions on what the best way to solve this is. @bgreg, this might be something you have some insight on.

**Comment by bgreg** [comment]
@ragesoss  I like what you got going on in https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/101a47b9020ef2548fd2c0411f8c354df483a635

**Comment by ragesoss** [comment]
Continued in https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1257

**Pull request closed without merging**
