### PR TITLE
tinymce-react and tinymce updated to Latest versions

### PR DESCRIPTION
**Pull request by hardy1334**
For the issue #2613   In this **Tinymce-react** and **tinymce** have been updated to their latest versions of **3.0.1** and  **5.0.2** respectively

### CODE REVIEW

**Comment by hardy1334** [comment]
@ragesoss  can you please have a look at it

**Comment by ragesoss** [comment]
It looks like this changes the theme. Can you add before/after screenshots, along with some explanation of the change (as in, was it just a renaming, or did they replace one theme with another, or what)?

**Comment by hardy1334** [comment]
**Before:** (Version _4.9.2)_

Screenshot from 2019-03-14 14-46-31

**After:** (Version _5.0.2)_

Screenshot from 2019-03-14 11-48-53

There are some changes in UI in version 5.0.2.

**Comment by ragesoss** [comment]
Hmm... I notice that the link icon and the list icons are no longer there in the version. Those icons are the result of the the `link` and `lists` plugins, which may not be working. We also use the `code` plugin to provide source HTML, so you should figure out if that is no longer working as well.

**Comment by hardy1334** [comment]
Current Version:

Screenshot from 2019-03-17 05-05-33

**Comment by bwreid** [comment]
@hardy1334 This looks pretty great to me! Thanks for working on this.

**Comment by ragesoss** [comment]
@hardy1334 did you look into the `code` plugin? It looks like that got removed in the PR.

**Comment by ragesoss** [comment]
Looks like it works with just adding it back in: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/160867af338995544b8b68318a0790723dd77251

**Comment by hardy1334** [comment]
@ragesoss  shall I add code plugin

**Comment by ragesoss** [comment]
I did already.

**Comment by ragesoss** [comment]
It adds it to the menu, which is how it was before. I think it doesn't need to be in the toolbar also.

**Pull request merged**
