### PR TITLE
Add initial Dockerfile support

### LINKED ISSUE #1787: Containerize the application for easy setup
I was trying WikiEduDashboard, but it takes sometime to get all prerequisites for a dev setup on some distributions such as Fedora. It may be nice to containerize the build (preferably docker) for easy setup. We can also add a make target to build the docker image locally and run it. In addition, publish/maintain an image on dockerhub also. I can take a stab at it.

### PR DESCRIPTION
**Pull request by tuxology**
Fixes #1787

This sets ground for using a containerized image for build/test an deploy. Currently this is a single image containing the DB as well as the complete application, but there can be options to separate the logic for flexible deployments using `docker-composer`. Apart from Docker volumens could also be used eventually and if the maintainers wish, we could publish a prebuilt image to Docker Hub or Docker Store from the official WikiEduDashboard org! 

As a reference for now, a prebuilt working WikiEdu dashboard image is at my own repo : https://hub.docker.com/r/tuxology/wiki-edu-dashboard/

To test run the pre-built image, 
```
$ docker pull tuxology/wiki-edu-dashboard
$ docker run --net=host -it tuxology/wiki-edu-dashboard
```

To build and run your own image,

```
$ docker build -t wiki-edu-dashboard .
$ docker run --net=host -it wiki-edu-dashboard
```

### CODE REVIEW

**Comment by ragesoss** [comment]
I ran into problems trying to start the image. It fails at the 'starting mariaDB' step.

```
sage@ragesoss-desktop:~/WikiEduDashboard$ docker run --net=host -it wiki-edu-dashboard
+ service mysql start
[FAIL] Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
```

This happened with both your image and the one I built.

In order to build this locally, I had to change the Dockerfile to specify Ruby 2.5.0. Ruby 2.5.1 was just released, so anything calling for Ruby 2.5 without a patch number will end up with 2.5.1, but the app is still on 2.5.0.

**Comment by tuxology** [comment]
> I ran into problems trying to start the image. It fails at the 'starting mariaDB' step.

Ok, looking

**Comment by tuxology** [comment]
@ragesoss Rather strange..I am unable to reproduce your failure. I purged all contaienrs and images on my machine and restarted docker daemon. Then, I pulled my image and ran it..

```bash
+ service mysql start
[ ok ] Starting MariaDB database server: mysqld ..
+ sleep 5
+ echo 'CREATE DATABASE dashboard DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE dashboard_testing DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      exit'
+ mysql
+ printf '$\n[DATABSE CREATED]\n'
$
[DATABSE CREATED]
+ echo 'CREATE USER '\''wiki'\''@'\''localhost'\'' IDENTIFIED BY '\''wikiedu'\'';
      GRANT ALL PRIVILEGES ON dashboard . * TO '\''wiki'\''@'\''localhost'\'';
      GRANT ALL PRIVILEGES ON dashboard_testing . * TO '\''wiki'\''@'\''localhost'\'';
      exit'
+ mysql
+ printf '\n[USER CREATED]\n'

[USER CREATED]
..
..
```

Docker inspect gives:

```
[
    {
        "Id": "sha256:7ffc0fafdcbbd730298f3a91e53b379683ed4aa6c9c13c20506c343decd2391c",
        "RepoTags": [
            "tuxology/wiki-edu-dashboard:latest"
        ],
        "RepoDigests": [
            "tuxology/wiki-edu-dashboard@sha256:7c70ee0f82a2c78414aa7e9fba87e2749c33388a8230d096493fe99ce79c3a77"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-04-02T05:57:17.039853707Z",
        "Container": "e545aa119e87dfb753f60e5ef6e26264cfecbc1fcdd52488447a27a9e74e8515",
        "ContainerConfig": {
            "Hostname": "e545aa119e87",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "RUBY_MAJOR=2.5",
                "RUBY_VERSION=2.5.0",
                "RUBY_DOWNLOAD_SHA256=1da0afed833a0dab94075221a615c14487b05d0c407f991c8080d576d985b49b",
                "RUBYGEMS_VERSION=2.7.6",
                "BUNDLER_VERSION=1.16.1",
                "GEM_HOME=/usr/local/bundle",
                "BUNDLE_PATH=/usr/local/bundle",
                "BUNDLE_BIN=/usr/local/bundle/bin",
                "BUNDLE_SILENCE_ROOT_WARNING=1",
                "BUNDLE_APP_CONFIG=/usr/local/bundle"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/sh\" \"-c\" \"'./entrypoint.sh'\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b3f3640d2d822a213e6d7dce583eadf651cf36b4471d05110d572239f7a7c54f",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "18.03.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "RUBY_MAJOR=2.5",
                "RUBY_VERSION=2.5.0",
                "RUBY_DOWNLOAD_SHA256=1da0afed833a0dab94075221a615c14487b05d0c407f991c8080d576d985b49b",
                "RUBYGEMS_VERSION=2.7.6",
                "BUNDLER_VERSION=1.16.1",
                "GEM_HOME=/usr/local/bundle",
                "BUNDLE_PATH=/usr/local/bundle",
                "BUNDLE_BIN=/usr/local/bundle/bin",
                "BUNDLE_SILENCE_ROOT_WARNING=1",
                "BUNDLE_APP_CONFIG=/usr/local/bundle"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "'./entrypoint.sh'"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b3f3640d2d822a213e6d7dce583eadf651cf36b4471d05110d572239f7a7c54f",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 2279721120,
        "VirtualSize": 2279721120,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5d3d0a03d303208ac7f0fb91e641c4edfe014ad5f65accc9bb4e281d55338a93/diff:/var/lib/docker/overlay2/24c0c08dca331e9e70c931cba56fcc211362f6d944bdf73eabbb7d10c236f5a2/diff:/var/lib/docker/overlay2/05608346efbc0cded24bd5f6cd4fa0988a9f8d8ea63a01fec6a61b2f03eff676/diff:/var/lib/docker/overlay2/7a11f09bef9d32dc03093f17d062621c597719eb3e9e171a72818e26535d191a/diff:/var/lib/docker/overlay2/95d65c4488f3839dd0e01ef18d40e0d2881096f3aef270aff4cc40bf71238685/diff:/var/lib/docker/overlay2/3079b822330c3425b7e9a6d5d7c6f7e619aca782d559b99f1ee6ffd6faa172b9/diff:/var/lib/docker/overlay2/219f2ed0898a063c6d5bfb054899ef157bba4f7379e34f4a674f90012b1b4d9d/diff:/var/lib/docker/overlay2/4d7c522d8cec42372b1a210ea170e2e75e5717ec6e4a4f815d1658356984ffad/diff:/var/lib/docker/overlay2/5646e6262d0fcbe91655bf2f08818f3bfc87286c1ac00630297b03f28f5006d9/diff:/var/lib/docker/overlay2/ed4f654240477d03aee5d3791d8feb0b1b11f0a7926b351764b95e6961dd81c1/diff:/var/lib/docker/overlay2/2f9de9f4fcbbc1270408b1ea4ddf83f59ad8bd048f4c3aa0ab7ada9a360641a2/diff:/var/lib/docker/overlay2/73537286dfaac584947b62df1dcf03c61733258edf6b141435945bc79c67ad31/diff:/var/lib/docker/overlay2/b89bb15ed1179a11a664c9f558594a5f46e15571695887312b6b98f47bd6127f/diff:/var/lib/docker/overlay2/1e61d1a661ca428b7e49474237bbd90c0a56196e1cce0ab79efebacc652d641e/diff:/var/lib/docker/overlay2/9cd9023cccb403c2e0cf57713386f60dc016a5d859e517978e0f2fdd9272f30d/diff:/var/lib/docker/overlay2/94af1f5ae6486af27a7d94364283b4103d505c451475dd11445538a0d14e0d06/diff:/var/lib/docker/overlay2/1af5ca6dbc4d66bccbac7452c533524f29f307d0576d1925dda9c875aa7a6894/diff:/var/lib/docker/overlay2/a069f0faefbae5286eda8a4245d9bf51a00acea83c0b09a2e3bcf2864c9eb73c/diff:/var/lib/docker/overlay2/ca86cf8eaca440b8114812ae8d29187bb298ea636f157164759cbc60cac0910c/diff:/var/lib/docker/overlay2/11f67b7028ae416fc212e9108d0018e662974db09e8b0d86d2608b73726a76c6/diff:/var/lib/docker/overlay2/674915d7291bbbe6e6290c1c5652629e271e3eafa31c9f54cbfa6941a80542ac/diff:/var/lib/docker/overlay2/32e84b02ad7d28566de88b889bb5998e21f101128dbaabb5e62be67ef22a6379/diff",
                "MergedDir": "/var/lib/docker/overlay2/fa2e92329d3a845cd31f15cae5820e9ac6d942bfdaeaa22f9ead5c5868229ed0/merged",
                "UpperDir": "/var/lib/docker/overlay2/fa2e92329d3a845cd31f15cae5820e9ac6d942bfdaeaa22f9ead5c5868229ed0/diff",
                "WorkDir": "/var/lib/docker/overlay2/fa2e92329d3a845cd31f15cae5820e9ac6d942bfdaeaa22f9ead5c5868229ed0/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:8568818b1f7f534832b393c531edfcb4a30e7eb40b573e68fdea90358987231f",
                "sha256:f7d58f7584447139266bdfe945c825a2a060f7fcbe0b07228ab97774f3a149ab",
                "sha256:a6afffb1947cf43119b7a7a87d9d752440f400866005d2f60e23f5c06abd91c1",
                "sha256:c8718ae77a2a4b3b9aeef18b67a64becf3b3b0a2715362c4b1a082d98d510009",
                "sha256:dfb4b932170cc6a66ffe4164182672777f8cc29b3443fea6fdd34b8e555462cf",
                "sha256:f0e246df7b6b9b7b8b54d3e47db59736b7dcdf7188f8bf3384875cdb1f9071ff",
                "sha256:fcc5480e465211f898088200aaeb840e7175914162200ea7e944cce6a68e0d29",
                "sha256:5e8e02b5e8a3bbecc5752e24982a72fd058cefd7de87095bd633414df9b4f29b",
                "sha256:c5fb96fa48b88e2b4c1ee2ddfb2ec5990491cbc96376a8266bff622977188ef9",
                "sha256:7890493c32ea0cbccff0d894c18876b21e1ea611dc1ca57d84a1e299a6d9fc78",
                "sha256:33d980c71b65e1f622e786b81f059e9a6d72443899c33b5477bf8ffb62f8ddfd",
                "sha256:a8a26fe33090a14f1bfa83fae8ece11e4a1227499e7df2d6f2fc368ca6ed0e7b",
                "sha256:64a0a8e79663553db31561a2a3e72ff8a0c13181eb71b6cfdba66caa84603dc5",
                "sha256:215d40a0bbbc0de739a86054ffe560533ae21f155a90950ddf1ed49b591515ba",
                "sha256:0f8c2440e7e183f98a8e15db5869cca7c985ba03aeaf81ad5b591c845a1fb50b",
                "sha256:55225a06bec779001c4007cb46a08b2207e14d60b614b76e2528b14d375ed0da",
                "sha256:efa572c39d09ff4683e14ebf3628866bf043fd2d954f40a18ed8c93b4559d343",
                "sha256:67159ab4fb47c97410d525201858f7f4426168de8ab25c25ac34bfddc5a6fe55",
                "sha256:92d8e7f461fd4ec576135cefc7bcad648746dd67aa888c110d68fc235740731b",
                "sha256:98fe680d05429b6f486c82c825e4e14cf4f72fe7caa29fb28f5bc624c0924999",
                "sha256:62bab8757fa34a4850b798f824faa7ace51aa2900d1d6262e0c9622d3bcd28d7",
                "sha256:bc69bd3b86bcec44a3be1f6abfbe8330a5973343359db444d2ee54c3a3fde930",
                "sha256:ee0c757d383774069e58c1cc134a0c21fc43b4f0e7128bd1d76506a72012d3d8"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by tuxology** [comment]
Made some changes such that the database is initialized within the image so we don't have to do it each time during a `docker run`. This would be nice for testing code, but DB changes won't persist. For that we would have to either use a docker volume/separate DB container. Considering we would use it for testing and not for production, I think it should be ok for now. We can eventually evolve this into a production ready image/images. I've also updated my Docker Hub image with these changes, so if you pull the latest `tuxology/wiki-edu-dashboard`, the dashboard bring-up would be a bit faster now.

**Comment by tuxology** [comment]
> Is this useful for development yet, or is the application code basically locked into the image? 

@ragesoss Currently, the code is locked in image but it is easy to get to a test environment using this setup. For example, you can do 
```
docker run --net=host -it -v /home/suchakra/Projects/WikiEduDashboard:/usr/src/app wiki-edu-dashboard
```

This will mount your local development directory to `WORKDIR` of the container for that specific run. You can change the code and test it live (watch for file changes). THe changes won't persist in the container.

For production environment, we can create a env variable that can be passed during docker image build. eg `ARG env=production` or `ARG environment=dev` This chooses the proper `gulp` command/or the proper entrypoint script as required. 

Ideally, we need a Makefile that wraps these docker commands such that it becomes as easy as 

```
make package-dev
make run-dev

make package-prod
make run-prod
```

The choice of ports to be used etc could also be configurable through this. I think for now, my idea was to use this Dockerfile for test and development purposes. I was planning to do this incrementally - improve the dockerfiles and add more features targeted towards real deployments or local development.

**Comment by ragesoss** [comment]
@tuxology cool. Maybe instead of having the docker info in setup.md, it should be in a new doc file — at least until we have a pretty well-tested and documented story for using docker as your dev environment. I wouldn't be comfortable with a newcomer seeing the docker instructions as the first setup option at this point. Otherwise, happy to merge this as a starting point for containerization.

**Comment by tuxology** [comment]
@ragesoss Ok, I will make the changes in the evening with usecases and documentation on how to use it

**Pull request merged**
