### PR TITLE
Added i18n in remaining texts

### LINKED ISSUE #5710: Button not translating
### What is happening?
The button "Find articles" on the "Articles>Available Articles" page do not translate himself in any language despite being translated on translatewiki. Others buttons are properly translated when changing the language in the language selector.

Oddly, the same "Find articles" button but on the home page of a project is properly translated.

### To Reproduce

1. Go to any project
2. Go on Articles>Available Articles
3. See the button "Find articles"
4. Change the language using the language selector
5. The button is not translated.

### Expected behavior
The button should be translated the same way the others are.

### Screenshots
Capture d’écran du 2024-03-19 18-38-59
Capture d’écran du 2024-03-19 18-39-09
Capture d’écran du 2024-03-19 18-39-16

### System Information

 - OS: Ubuntu 23.10
 - Browser: Firefox
 - Version: 124.0

### PR DESCRIPTION
**Pull request by prathamVaidya**
## What this PR does

Fixes  #5710 

## Screenshots

Before:

image

After:

image

### CODE REVIEW

**Comment by prathamVaidya** [comment]
@ragesoss how about using this linting rule `i18next/no-literal-string` from https://github.com/edvardchen/eslint-plugin-i18next.

image

After trying in wikiDashboard

image

**Comment by ragesoss** [comment]
> @ragesoss how about using this linting rule `i18next/no-literal-string` from https://github.com/edvardchen/eslint-plugin-i18next.
> 

@prathamVaidya will that break the build, or just provide editor integration?

**Comment by prathamVaidya** [comment]
> > @ragesoss how about using this linting rule `i18next/no-literal-string` from https://github.com/edvardchen/eslint-plugin-i18next.
> 
> @prathamVaidya will that break the build, or just provide editor integration?

It will be only shown in the editor and the browser eslint window only on the opened file.  It will not break the build.

image

image

**Comment by ragesoss** [comment]
cool, that sounds useful.

**Comment by prathamVaidya** [comment]
> cool, that sounds useful.

Opened #5735

**Pull request merged**
