### PR TITLE
Redirect when users visit /update_locale/:locale to change languages

### PR DESCRIPTION
**Pull request by ragesoss**
This will save a bit of confusion when we direct users to update their locale via https://dashboard.wikiedu.org/update_locale/en

### CODE REVIEW

**Comment by ragesoss** [comment]
@bwreid is there anything you'd do differently here? I want to learn what I can from you while your eyes are still fresh on this codebase!

**Comment by bwreid** [comment]
Looks pretty solid to me! Should we do anything for users that end up [at the wrong place](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/7c62faab08998bd193bf8e1eb590806d7d98be5e/app/controllers/users_controller.rb#L30-L33) as well?

As a side note, I'm assuming users get here just based off of something a staff member tells them?

**Comment by ragesoss** [comment]
@bwreid I don't think the failure condition really needs any special handling; it should be extremely rare, is likely to be confusing no matter what.

Yeah, someone asks about it maybe once a term or less, and just point them to https://dashboard.wikiedu.org/update_locale/en

**Comment by ragesoss** [comment]
I guess one possible approach to improve that would be to insert the language picker even on dashboard.wikiedu.org _if the user's locale is not English_.

**Comment by ragesoss** [comment]
I had second thoughts about it. I think it might be weird to have that language picker show up by default, then you change your language to English (because it's there, so you are invited to play around with it), and after that it's gone. I think if we went that route, it would be more like:

* show language picker if user locale is not English *or* if user has an explicit locale preference set on their user record.

**Pull request merged**
