### PR TITLE
replaced few more lines of jquery to Vanilla Js in nav.jsx

### PR DESCRIPTION
**Pull request by Manasa2850**
## What this PR does
< Solves #3675  >

### CODE REVIEW

**Comment by ragesoss** [comment]
@Manasa2850 is this working locally for you? The failing tests all appear to be related to the navbar.

**Comment by Manasa2850** [comment]
@ragesoss yes I saw the failing tests. I'll try fixing them. Thanks!

**Comment by Manasa2850** [comment]
@ragesoss this is working fine locally for me. Could you please help me resolve the build errors?

**Comment by ragesoss** [comment]
@Manasa2850 I'm not sure what might have been going wrong, but I've just merged a different PR that closes the issue.

**Comment by Manasa2850** [comment]
Ok no worries!

**Pull request closed without merging**
