### PR TITLE
[WIP] Permanently exempt rubocop rule: FormatStringToken

### PR DESCRIPTION
**Pull request by kaine119**
Moves the `Style/FormatStringToken` in rubocop.yml to permanent exemptions; it's not applicable if only string interpolation (#{foo}) is used.

(from #2173)

### CODE REVIEW

**Comment by kaine119** [comment]
The same spec failed in [the first test](https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/449328001#L4440) but passed in [the second test](https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/449328002#L4885), is that normal?

**Comment by ragesoss** [comment]
Yeah, that happens every once in a while with that spec in particular. If the second, more complete test suite passes, then generally everything is fine. I restarted the first one, which will probably pass.

**Comment by ragesoss** [comment]
Are there even any violations of this rule? If not, we may as well just enable it.

**Comment by kaine119** [comment]
There aren't any violations of this, don't think [`Kernel::format`](http://ruby-doc.org/core-2.5.3/Kernel.html#method-i-format) is used anywhere.

**Comment by kaine119** [comment]
Should I just delete the config line for this rule?

**Pull request merged**
