### PR TITLE
Training translations#1514

### PR DESCRIPTION
**Pull request by bcb37**
Added internationalization to parts of the training slides, including:
- The text of quizzes - if translations exist on the media wiki
- Some inline UI text
- The slide menu (table of contents)

Added corresponding entries in the English locale file.

### CODE REVIEW

**Comment by ragesoss** [comment]
@bcb37 is this still a WIP? Are those two failing specs just ones where the feature hasn't been implemented yet?

**Comment by bcb37** [comment]
@ragesoss they all passed before I pushed it. I'll take a look.

**Comment by bcb37** [comment]
Ok, yeah it's a WIP.

**Comment by bcb37** [comment]
Trying to figure out why they pass for me but fail here.

**Pull request merged**
