### PR TITLE
Added References Graph for articles

### PR DESCRIPTION
**Pull request by khyatisoneji**
**Screenshots:**

**Before:**

**ORES:**
image

**Article Development:**
image

**After:**

**ORES:**
image

**Article Development:**
image

### CODE REVIEW

**Comment by khyatisoneji** [comment]
If you feel, updating ORES graph for a range of references added values is not necessary/important, I can undo those changes

**Comment by ragesoss** [comment]
I think these would work better as line graphs, rather than step graphs.

**Comment by khyatisoneji** [comment]
Made condition for small values( < 8) take value 8

**Comment by ragesoss** [comment]
Cool!

I don't think the control for changing the interpolation is useful.

Other than that, this looks great!

**Comment by ragesoss** [comment]
This looks good, but I noticed that it is a lot slower to switch between graphs than it was before. Do you know what is bogging down performance?

**Comment by khyatisoneji** [comment]
No, it's working fine with me

**Comment by ragesoss** [comment]
How many revisions are in the article(s) you've tested it with? It might be something that only bogs down when the revision count gets higher.

**Comment by khyatisoneji** [comment]
Not more than 10 revisions

**Comment by khyatisoneji** [comment]
Removed unnecessary code

**Comment by ragesoss** [comment]
I couldn't ever figure out why this had a performance problem for me. This work will probably be useful if someone takes this up again in the future.

**Pull request closed without merging**
