### PR TITLE
Add unknown to other wikidata updates

### PR DESCRIPTION
**Pull request by 1v4n4**
The Sum of other and unknown updates is displayed as Other updates in the course.json and WikidataOverviewStats component.
I added a views helper method for adding unknown to other updates and removing from stats hash. The plan is to use that method for Wikidata stats in campaigns also.

The info is removed from Redirects created.

After:
other
otherjson
Before:
otherjsonbefore
otherbefore

### CODE REVIEW

**Comment by ragesoss** [comment]
I think these should be added together server-side so that the Rails version of number_to_human remains the only one we use. Otherwise, there will be inconsistent internationalization (since the Rails version automatically takes account of locale when producing the 'human' versions of numbers).

**Comment by 1v4n4** [comment]
Ok. So I should leave CourseStats as it is, but add unknown to other updates for course.json, right?

**Comment by ragesoss** [comment]
Yes, exactly.

**Comment by 1v4n4** [comment]
This test is ok at my place and I don't think it is related to what I'm doing here.
test

**Comment by ragesoss** [comment]
Yes, this was caused by wikiedu.org being down while the tests ran. I've restarted build, to make sure no later tests were broken.

**Pull request merged**
