### PR TITLE
Update enzyme to v3.1.0

### PR DESCRIPTION
**Pull request by sljohnson32**
This PR addresses issue #1452 

After updating the version of Enzyme to 3.1.0, we added enzyme-adapter-react-15 to the dev dependencies and used it to configure an adapter in the testHelper.js. We also installed react-test-renderer which we are using to render React components as pure JS objects. 

Based on the documentation for upgrading [here](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md), we updated tests to pass by replacing any references to `.nodes()` with `.getElements()` and any references to `.node()` with `.instance()`.

### CODE REVIEW

**Comment by ragesoss** [comment]
@sljohnson32 the javascript test suite is failing hard with this change. You can `jest` locally to run the js tests and see the errors.

**Comment by sljohnson32** [comment]
@ragesoss We just noticed those errors after installing Yarn and running tests again locally.  We will work on getting those fixes in tomorrow.

**Comment by sljohnson32** [comment]
@ragesoss We pushed up a fix for the testing issue.  All tests are now passing.

**Comment by ragesoss** [comment]
@sljohnson32 thanks. I fixed the package.json conflicts on a new branch, and will merge that if it passes.

**Pull request merged**
