### PR TITLE
adds wrapping in arrange timeline

### PR DESCRIPTION
**Pull request by shivanshbindal9**
pr2

### CODE REVIEW

**Comment by ragesoss** [comment]
Thanks! This looks like a bit of style regression for single-line titles: the whitespace is no longer symmetric above vs. below the title, and the text is smaller. Ideally the fix should allow wrapping but otherwise leave the style as-is.

**Comment by ragesoss** [comment]
Wow, that's multiple kinds of bad layout!

Fixing the red border so it don't go under the block as well would be nice, although that can be a separate issue if necessary.

**Comment by ragesoss** [comment]
@shivanshbindal9 are you planning to continue working this issue? As I said above, I think with a few further tweaks, we can fix all the main problems.

**Comment by shivanshbindal9** [comment]
Yes, I will try to fix it!

**Comment by ragesoss** [comment]
I think this is largely fixed now.

**Pull request closed without merging**
