### PR TITLE
adds react-select in home_wiki_project_selector

### PR DESCRIPTION
**Pull request by shivanshbindal9**
home_wiki

### CODE REVIEW

**Comment by ragesoss** [comment]
Looks like the feature spec for changing the home wiki is broken: `spec/features/course_page_spec.rb`:

https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/470180847#L5989

Probably just needs to be tweaked so that it finds the new element, instead of looking for one that no longer exists.

**Comment by shivanshbindal9** [comment]
@ragesoss I have modified the tests .

**Comment by shivanshbindal9** [comment]
Can you please review it !! @ragesoss

**Comment by ragesoss** [comment]
@shivanshbindal9 nice, thanks! Feel free to take on the remaining selects. :-)

**Pull request merged**
