### PR TITLE
feat: Add visual indicator for closed courses

### LINKED ISSUE #6050: Make it easy for Wiki Education staff to see when a course has been closed
### Current Behavior:

Wiki Education staff go through a process of 'closing out' courses at the end of each term, which uses the `closed_date` flag to add a timestamp for when the course was closed. (This indicates that there is nothing left to do in terms of reviewing work, moving good sandbox drafts into Wikipedia mainspace, updating the end date to capture any student edits that happened soon after the original end date, evaluating the average quality of student work, and logging any major problems.)

The closing process happens in Salesforce and gets logged on the course flags via the `UpdateCourseFromSalesforce`, and there is no UI related to it on the Dashboard side.

### Desired Behavior:
When an admin on Wiki Education Dashboard views a course that has already been closed out, it should be obvious that it has been closed.

#### ~~On the course page~~ (done)

The Admin Quick Actions component is probably the best place to indicate this. It should be prominent, eg, by affecting the background color in addition to a text indicator.

#### On the campaign course list

Closed courses could be highlighted similarly to the way we highlight just-started courses, soon-to-end courses, and private courses. This highlighting feature should only affect admins, and it should be implemented similarly to the existing highlights, which use methods from course_helper.rb to determine whether to apply a CSS class that applies the color to the row for that course.

### PR DESCRIPTION
**Pull request by swayam-agrahari**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
 This PR introduces a visual indicator for courses that have been "closed out" by Wiki Education staff.

## Screenshots
Before:
image
Screenshot from 2024-12-18 00-41-41

After:

Screenshot from 2024-12-18 00-28-25
Screenshot from 2024-12-18 00-26-17

closes #6050 

## Open questions and concerns
 Please let me know if this works or if further changes are needed!

### CODE REVIEW

**Comment by ragesoss** [comment]
This looks great! I don't think the 'All review work...' half of the message is needed. Admins who will see this know what 'closed' means.

Showing a 'closed' indication on the campaign view is also a good idea, but I'd prefer leaving that to a separate PR. I will add notes about how that ought to work, on the issue description.

**Comment by swayam-agrahari** [comment]
Thank you for the feedback!
I've removed the "All review work..." sentence as suggested. For the campaign view 'closed' indication, I can handle it in this PR if you'd prefer.
If not, do I need to raise an spearate issue for campaign view,if not included in this pr?
 Let me know how you'd like me to proceed!

**Comment by ragesoss** [comment]
I prefer a separate PR, but you can mention the same issue for the campaign view.

**Comment by swayam-agrahari** [comment]
Hello @ragesoss , I have removed the additional texts and styles from campaign view. 
I will make a pr for campain view as you requested asap : )

**Pull request merged**
