### PR TITLE
[WIP] Splitting CoursesController (issue #1417)

### PR DESCRIPTION
**Pull request by testa19**
Steps on orginizing Courses Controller structure https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1417

1. Splitting CoursesController: CoursesUpdateController created (no modules or namespaces)

### CODE REVIEW

**Comment by ragesoss** [comment]
It worked! It looks like that was a relatively straightforward refactor:
* move update and its helper methods
* move the section of the specs that test `#update`
* add new explicit routing for update, and add routing exception for basic course resource routing

What do you think about this structure versus going down the namespace path?

Cleanup remaining:
* Don't change `consider_all_requests_local`
* Fully remove commented-out code that was copied to new files

**Comment by testa19** [comment]
@ragesoss Oh, it was fust a first step: to see how two separate controllers wil look and work.
Now i'm trying to understand things (and make them work) with namespacing or modules:
and seems i am missing something

**Comment by testa19** [comment]
@ragesoss can't make them work with namespacing: had a mess with partials - there is too much interlacement (with other controllers? in routes?) for my qualification.

**Comment by ragesoss** [comment]
I'm fine with doing it the first way, if you can't figure out the namespacing solution. If it's not a straightforward refactor, then maybe it's best to not introduce namespacing, which I haven't used well enough to feel totally comfortable with myself.

**Comment by ragesoss** [comment]
Please reopen if you take this up again, although it now has conflicts with the main branch.

**Pull request closed without merging**
