### PR TITLE
[WIP] Move number formatting to client side

### PR DESCRIPTION
**Pull request by yunjuc**
Fixes for #1853 

I tried a couple of approaches to do this:
1. There is a jquery method can create number animation, I add some code so the animation and number formatting can happen at the same time. This works on campaign stats now.
2. I found a [react component](https://www.npmjs.com/package/react-countup) can create number animation, but it can't do number formatting and these two actions need to happen together. If we want to have both animation and the format, I'll need to dig into the source code and change it.

I read about using jquery in react is not a good idea. Now I have a numbers.js holds the animation code (a jquery method) and number formatting function. What I want to do is to add a script link on the head so it can select the numbers and run the code, similar to i18n, but only on the course and user profile pages.

For maintenance point, which one will be the better way to do it?

### CODE REVIEW

**Comment by ragesoss** [comment]
@yunjuc thanks! I'll take a look at this tomorrow.

One quick thing: the number formatting and the update animation should be done i separate PRs.

For the animation, I had imagined something that could be implemented just with CSS, so that adding a certain class (via React) would trigger the animation. I'm not an expert with CSS animations and maybe that's not practical, but I think it's the ideal in terms of maintainability, separating the logic part of it — in this circumstance, trigger some sort of visual effect — and the actual visual effect styling. I hadn't thought of animating the actual increase, like the `react-countup` package you found. I like that concept, although it sounds like it's not a good fit for any numbers that we want to treat with some kind of 'for humans' reformatting. The core of the feature will just be to draw the eye whenever stats do update, so that (for example) if a course page is being projected on a screen at an event, there will be some kind of change that lasts for a few seconds and increases the chances that people will notice that the numbers changed.

**Comment by yunjuc** [comment]
My bad. I tried another way approached to indicate the data update - to add and remove elements from the dom, something like this. 
https://jsbin.com/tocokop/edit?html,js,output

I use Mutation Observer to watch the dom, so I need to add a js script link to the course page. How can I do that?

I'll open another PR from the data update visual cue, and keep this one as number formatting change.

**Comment by yunjuc** [comment]
Since now I move to another direction on the animation so it's not number depended. Is there still a need to move the number formatting to frontend? What's the benefit of it?

**Comment by ragesoss** [comment]
@yunjuc I think the benefit of moving the number formatting to the frontend is pretty minimal. For React views where the HTML is completely rendered client-side, it's a little nicer to have everything related to localization and formatting also done client-side, just to consolidate display-related logic in one place (and to make the API data a bit more usable for potential 3rd-party consumers: if we're providing numbers directly from the API, they'll be more useful as real numbers than strings like `'100k'`).

The easiest fix for the too-large bytes-added figures would be to format those server-side, but it means adding more display logic to the server (so it's basically adding a small amount of technical debt for when we eventually straighten that out and move the display logic to the client). But until we have a solution that brings all the for-humans formatting together in one place, it's probably better to just do the easiest thing that will work.

I did find this project — https://github.com/emcien/number-helpers-coffeescript — which is aimed at the problem we have, but it doesn't support locales, unfortunately.

**Pull request closed without merging**
