### PR TITLE
Update docker and implement docker compose for development

### PR DESCRIPTION
**Pull request by raffifu**
## What this PR does
This PR closes this issue https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/4683 to separate MySQL and Redis service  into independent service with docker compose. Docker compose will lower the barrier of setup dev environment on host machine without changing the dev experience because the docker compose will mount project directory directly to container.

## Screenshots
image

## Open questions and concerns
- Currently the implementation of Dockerfile and docker-compose only for development. Is there any concern to provide docker image for production use?
- I think, in the future the rails and react can be separated into individual service, because now the `app` container will run rails and react

### CODE REVIEW

**Comment by ragesoss** [comment]
Thanks for working on this! If I follow the updated docker.md instructions, I should end up with a working development environment? I don't normally use docker.

**Comment by raffifu** [comment]
Yes, it will work as development environment. The development experience will going to be the same  as working on host machine. The development feature like automatic reload will works out of the box

**Comment by ragesoss** [comment]
Thanks. I will test this out when I get a chance. Is it possible to move the create-db.sql file into a Docker-specific directory? I think it might confuse people who are not using docker.

**Comment by raffifu** [comment]
Okay, i have commit the new changes. Now every file related to docker is inside the docker folder

**Comment by ragesoss** [comment]
I tried the first command, `docker built -t wiki-edu-dashboard .`, but I get the following error:

```
unknown shorthand flag: 't' in -t
```

**Comment by raffifu** [comment]
I think there's a typo on your command. It should be `docker build -t wiki-edu-dashboard .`

Args:
`-t`: name a tag on docker image 
`.`: The folder location of Dockerfile

**Comment by ragesoss** [comment]
I was not able to get it working. The `init` container is exiting:

```
[+] Running 6/6
 ✔ Network wikiedudashboard_default      Created      0.1s 
 ✔ Volume "wikiedudashboard_mysql_data"  Created      0.0s 
 ✔ Container wikiedudashboard-mysql-1    Healthy     22.1s 
 ✔ Container wikiedudashboard-redis-1    Healthy     22.1s 
 ✔ Container wikiedudashboard-init-1     Exited      25.7s 
 ✔ Container wikiedudashboard-app-1      Created      1.5s 
service "init" didn't complete successfully: exit 1
```

**Comment by raffifu** [comment]
Hii @ragesoss, Thank you for reviewing this PR. I have updated the file docker-compose on the latest commit. That error happen because i forgot to update the location of `init-db.sql` inside the folder `docker`. You can try to run again with command
```
# Run inside the folder WikiEduDashboard
# Ensure to stop all container and delete volumes
$ docker compose down --volumes

# Run again
$ docker compose up
```

**Comment by ragesoss** [comment]
It worked!!!! Excellent.

**Pull request merged**
