### PR TITLE
Issue#2520

### LINKED ISSUE #2520: Change passcode detail to be a link
image

Most instructors don't need the passcode as much as they need the actual link to send out to students to enroll. When the details section is _not_ being edited, we should change the passcode from plain text to actually being the enrollment link. When editing, the regular fields should still show.

### PR DESCRIPTION
**Pull request by twisted-sres**
Fixes #2520 
screenshot from 2019-03-05 00-53-20
Hey, it looks like this, but I guess there is some problem with courseLinkParams, it is not able to fetch the home page address and hence it is displaying undefined instead of it.

### CODE REVIEW

**Comment by ragesoss** [comment]
The base URL comes from the course slug. `courseLinkParams` is used in some places as the base URL, but for the `Details` component that is not included as either a prop (as in `CourseAlerts`) or as a function (as in `EnrollButton`. However, the slug itself is included as the `course_id` prop in `Details`.

**Comment by twisted-sres** [comment]
Hey, now it looks like this, the link is breaking between the lines, should I increase the width of the details box, but that would cover most of the page then.
screenshot from 2019-03-05 02-09-30

**Comment by ragesoss** [comment]
I think rather than showing the whole link (and labelling it Passcode), it could be with `Enrollment link` with the target being the URL, and ideally with a functional `copy to clipboard` icon button next to it. Then the user could either click on the URL and copy it from the browser, or copy it straight to the clipboard to paste it into a an email.

**Comment by twisted-sres** [comment]
Do we have this copy to clipboard button anywhere else in this project?

**Comment by ragesoss** [comment]
No, I don't think we do. You can find an example here of a change that involved adding a new icon: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/4455c50328bc03ad02a7b35fe1ea73e4857b8c1e

For sourcing the icon, you could either find a freely licensed one from commons.wikimedia.org or The Noun Project, or create a new one.

**Comment by twisted-sres** [comment]
Hey, can I implement copy to clipboard functionality using react-copy-to-clipboard package?
But that would include changing gitignore files as well

**Comment by twisted-sres** [comment]
I have installed the copy-to-clipboard npm package in the node_modules folder, how do I import it? Is there anything similar which I could look on?

**Comment by twisted-sres** [comment]
screenshot from 2019-03-08 01-19-29
@ragesoss how about this? The link gets copied on clicking on the text area and a Copied message is displayed. This way we are showing the link also.

**Comment by ragesoss** [comment]
It's moving in the right direction, but I don't like using an un-editable input field for this purpose.

I think, in this case, a cleaner UI is a higher priority than showing the full URL.

**Comment by twisted-sres** [comment]
@ragesoss so basically for copying, we need to select first and then copy, and select function is only supported for textarea, so one approach can be having a textarea but hiding it and having a button which would trigger the textarea select and copy. Haven't seen copy without textarea. Can't think of any other approach.

**Comment by ragesoss** [comment]
@twisted-sres I see there are a few examples of doing it without a text area, eg, https://css-tricks.com/native-browser-copy-clipboard/

**Comment by twisted-sres** [comment]
Okay, thanks, will try implementing it, I had few queries and wanted to chat on direct message on slack, is it possible?

**Comment by ragesoss** [comment]
Please re-open if you take this up again. Thanks! Your progress will likely be useful for whoever finishes this up.

**Pull request closed without merging**
