### PR TITLE
add redux logger:

### PR DESCRIPTION
**Pull request by KarmaHater**
+ Add Redux Logger for easier development

npm package added
https://github.com/evgenyrodionov/redux-logger

### CODE REVIEW

**Comment by KarmaHater** [comment]
@ragesoss Any idea as to why my tests are failing on Travis?

**Comment by ragesoss** [comment]
@KarmaHater it's because of `eslint` errors in the `gulp build` step:

```
/home/travis/build/WikiEducationFoundation/WikiEduDashboard/app/assets/javascripts/utils/router.jsx

  43:20  error  Unable to resolve path to module 'redux-logger'  import/no-unresolved

/home/travis/build/WikiEducationFoundation/WikiEduDashboard/app/assets/javascripts/components/user_profiles/graphs/as_instructor_graphs/courses_taught_graph.jsx

  20:13  error  Expected indentation of 10 spaces but found 12  indent

  21:15  error  Expected indentation of 12 spaces but found 14  indent

  22:15  error  Expected indentation of 12 spaces but found 14  indent

  23:15  error  Expected indentation of 12 spaces but found 14  indent

  24:13  error  Expected indentation of 10 spaces but found 12  indent
```

The `no-unresolved` is maybe because the new package only got added to package.json and not to yarn.lock.

The indentation is weird; we saw that same error about indentation in that file in someone else's environment because of having a different version of eslint installed (I think) but in this case, no related module or code was changed so I'm not sure what's happening.

**Comment by KarmaHater** [comment]
Hmm.. I added it with yarn. I will just delete it and add it again. Thanks!

**Comment by ragesoss** [comment]
That fixed the gulp error, but it looks like most of the feature specs are failing. I'm getting the same failures locally. I don't see an obvious cause, and it seems to be working normally in my browser.

(Also, the change to yarn.lock wasn't included in the commit.)

**Comment by KarmaHater** [comment]
Im going to close this and try another branch. Who knows what the issue is.

**Pull request closed without merging**
