### PR TITLE
Add alerts when Articles are moved out of mainspace to different namespaces

### PR DESCRIPTION
**Pull request by sharon-odhiambo**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
This PR adds an alert to a Wiki expert when a student moves an article associated with their course out of mainspace to a different namespace like User or Draft. 

## Screenshots
Before:
< add a screenshot of the UI before your change >

After:
< add a screenshot of the UI after your change >
## Open questions and concerns
< anything you learned that you want to share, or questions you're wondering about related to this PR >

### CODE REVIEW

**Comment by ragesoss** [comment]
It looks like this is starting from your earlier work with the setup process. I can review it more easily if you rebase or cherry-pick the work for this specific issue onto a clean branch.

**Comment by ragesoss** [comment]
In broad strokes, I think this is going in the right direction. I can provide some detailed feedback once it's put into a clean branch. (See `docs/git.md` if you need some guidance on how to do this with git.)

**Comment by sharon-odhiambo** [comment]
Hi @ragesoss , sure lemme do that. I'm struggling a bit with connecting between this and the alert process in the frontend.

**Comment by sharon-odhiambo** [comment]
For now lemme close this and create another PR with a clean branch.

**Pull request closed without merging**
