### PR TITLE
Fix AssignButton popover to word-wrap text at bottom-#3715

### PR DESCRIPTION
**Pull request by mattwarren10**
## What this PR does
Add simple word-wrap that breaks at each word to the assign button popover: issue #3715

## Screenshots
Before:
assign-button-popover-#3715

After:
Screen Shot 2020-02-01 at 9 01 40 PM

### CODE REVIEW

**Comment by bwreid** [comment]
@mattwarren10 This looks great to me! Very small thing, but can you change the added CSS to be in the same format as the rest of the file? I.e. no `:` or `;`.

Thank you!

**Comment by mattwarren10** [comment]
@bwreid check it again

**Comment by bwreid** [comment]
Taking a look at this again, this now leads to a different problem in that any article with a space will be shortened so that the box will appear very small.
image
This isn't too terrible, but ideally this box would:
* Have a standard width to show most articles
* In the event that an article name goes over, it carries to the next line

I believe this could be achieved by setting a `width` and `max-width` for one of the popover elements. Don't spend too long on this! If you get stuck, let me know and I'll take a crack at it.

Thanks for your hard work!

**Comment by bwreid** [comment]
@mattwarren10 Hi Matt -- looks like you got some odd stuff merged in. I roll back your changes to before the merge and then remake just _your_ changes. If that's proving tricky, just let me know.  :)

**Comment by ragesoss** [comment]
As you noted, the main issue got solved along the way with the layout change to the Students tab.

There are still some edge cases where the popover listing the assigned articles can go offscreen, but they seem more related to #2012 than anything else.

**Pull request closed without merging**
