### PR TITLE
changed uploads page for mobile phones

### LINKED ISSUE #3660: disordered uploads page in mobile phones
WhatsApp Image 2020-01-13 at 11 24 42 PM

### PR DESCRIPTION
**Pull request by Manasa2850**
## What this PR does
< fixes #3660 >

## Screenshots
Before: 
before

After(in mobile): 
WhatsApp Image 2020-01-15 at 7 15 58 PM(1)

After(in desktop):
WhatsApp Image 2020-01-15 at 7 15 58 PM

 
## Open questions and concerns
< I have selected max-width as 800px so that it works fine even in devices like iPad and Kindle Fire.>

### CODE REVIEW

**Comment by Manasa2850** [comment]
@ragesoss could you please review my prs so that I can start working on a new issue.

**Comment by ragesoss** [comment]
@Manasa2850 looks like this causes a regression in the desktop view:

regression

**Comment by Manasa2850** [comment]
I'll resolve it.

**Comment by ragesoss** [comment]
Vinit is also working on this, and the same comment applies: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3670#discussion_r367060984

**Comment by Manasa2850** [comment]
@ragesoss I have made the changes you suggested.

**Comment by Manasa2850** [comment]
@ragesoss could you please check this.

**Pull request closed without merging**
