### PR TITLE
WIP to test a React component with Mocha

### PR DESCRIPTION
**Pull request by ragesoss**
@bmathews Have you done testing with Mocha before? I'm trying to get a React test running, but I just can't crack it. I've been trying out various snippets and tools from these blog posts: 
* http://www.bebetterdeveloper.com/coding/getting-started-react-mocha.html
* http://www.asbjornenge.com/wwc/testing_react_components.html
* http://www.parrisstudios.com/?p=581

But none of them get me all the way to being able to run `TestUtils.renderIntoDocument` on a React component.

### CODE REVIEW

**Comment by bmathews** [comment]
I have! Let me check out your branch and see what the deal is.

**Comment by bmathews** [comment]
This the error you're seeing?

```
 3   -_-_-_,------,
 1   -_-_-_|   /\_/\
 0   -_-_-^|__( x .x)
     -_-_-  ""  ""

  3 passing (111ms)
  1 failing

  1) Modal adds the modal-open class:
     ReferenceError: $ is not defined
    at [object Object].React.createClass.componentWillMount (app/assets/javascripts/components/common/modal.cjsx:5:5)
    at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:228:14)
    at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:38:35)
    at mountComponentIntoNode (node_modules/react/lib/ReactMount.js:248:32)
    at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:134:20)
    at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:269:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:110:20)
    at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:404:18)
    at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:493:32)
    at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:52:18)
    at Context.<anonymous> (test/components/modal-test.coffee:12:27)
```

**Comment by ragesoss** [comment]
That's one of many I've seen. :)

But yeah, that's the one I got stuck on most recently.

**Comment by bmathews** [comment]
To avoid this particular issue, it'd be best not to rely on a global instance of jQuery being available. jQuery can be installed via npm and required like any other module. Everything in our bower.json can _probably_ be required as an npm module instead. 

If we don't feel like doing that, we'd have to run the tests in a browser (headless, ideally):
https://mochajs.org/#running-mocha-in-the-browser

**Comment by bmathews** [comment]
If you replace those lines two usages of $ in `modal.cjsx` with `document.body.classList.add('modal-open')` and `document.body.classList.remove('modal-open')`, the test passes. `classList` is IE10+, though.

**Comment by ragesoss** [comment]
Thanks @bmathews!

I'm not sure what all is involved with switching to a jquery module instead of a global, but since we just use a few bits of jquery functionality here and there, it seems like switching to requiring it where we need it would be a good step forward.

For now, I didn't want to meddle with the components, though. Your comment about global jquery and npm led me to a guess of trying installing jquery as a dev dependency, and then doing `global.$ = require 'jquery'`.  That worked!

**Pull request closed without merging**
