### PR TITLE
Enable Rails/I18nLocaleTexts and translate the admin page flash notice

### PR DESCRIPTION
**Pull request by sharon-odhiambo**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
In this PR, I enabled the Rails/I18nLocaleTexts linting rule to disallow untranslated versions of flash notices. On this I updated the "You don't have access to that page" translation to different languages on the admin page to allow all users understand the warning and proceed with the necessary authentication and authorization
It's in line with this issue  - https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/5297

## Screenshots
Before:
Screenshot from 2023-03-15 16-42-38

After:
Screenshot from 2023-03-15 16-43-18

## Open questions and concerns
 I'm wondering whether we can have a gem that utilizes translatewiki.net to automatically translate the remaining flash notices to the other languages

### CODE REVIEW

**Comment by ragesoss** [comment]
This is definitely a rule we want to add to the permanent exceptions; we exclusively use human translations from translatewiki.net, and as long as every message is in the en.yml, there will be fallback messages for any languages that have some missing translations.

**Comment by sharon-odhiambo** [comment]
Okay, lemme do that.

**Comment by ragesoss** [comment]
This PR should only disable that rule. I don't want to include any of the machine translations.

**Comment by sharon-odhiambo** [comment]
Okay let me revert the commit. Thank you for the feedback.

**Pull request merged**
