### PR TITLE
View as student mode to course page

### PR DESCRIPTION
**Pull request by Kartik1397**
Allows instructor to see the course home interface as their students see it.
Issue: #3503 
## Screenshots
captured
Screenshot from 2019-12-12 04-26-51
Screenshot from 2019-12-12 04-27-25

### CODE REVIEW

**Comment by ragesoss** [comment]
Hi @Kartik1397! I am really interested in this PR, but haven't had a chance to dive into yet. Looks like it's accumulated some conflicts in the meantime as well.

Can you say more about the strategy you've taken? This is a complicated feature that has a number of possible ways it could lead to subtle bugs, so an overview of how you're thinking about the changes will be really helpful for me in evaluating it.

It will also be really helpful to clean up the commit history, such as by rebasing the changes on the latest code so that only changes that are relevant to the issue will be in the PR.

**Comment by Kartik1397** [comment]
I added `isStudent` role for instructor [dd4d1283a1bc62075a0b96f410d2fcda0c337270] then whenever we select student from popover ofViewAsStudent button user id of intructor is changed with user id of student and `viewAsStudent` state is changed to true which was initially false and disabled all the buttons which can change student's data.

**Comment by Kartik1397** [comment]
Thanks @ragesoss for taking interest in this PR. I am also very interested in working on this PR again. I will rework on this PR after a week.

**Comment by ragesoss** [comment]
Please reopen if you decide to take this up again.

**Pull request closed without merging**
