### PR TITLE
 Fix 4466/Finalizing with remaining icons

### LINKED ISSUE #4466: Standarize the usage of icons in the UI
Icons are implemented in different ways throughout the app. There's an 'icon font' (`app/assets/fonts`) which hasn't been updated in a long while but it still used for some icons, via CSS classes. There are also a variety of SVG icons (`app/assets/images`) which are used as background images for CSS classes, and there are some SVG icons defined directly in JSX components (eg, `enroll_card.jsx`).

Identify the best pattern for handling icons throughout the app and standardize it so that all icons are implemented the same way.

### Related Files & Code:

* `app/assets/stylesheets/_icons.styl`

### PR DESCRIPTION
**Pull request by ujjwalpathaak**
Fixes #4466 
## What this PR does
Hi @ragesoss 
I have added more changes to the previously open PL which had only the arrow icons changed. 

I have changed all the icons which were being used as font files in ```app/assets/stylesheets/_icons.styl```

old PRs for the same issue (for refs) - 
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5544
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5538
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5542

### CODE REVIEW

**Comment by ujjwalpathaak** [comment]
@ragesoss Hello ✋🏻 
I see out of 1835 examples, 317 are failing. Which is happening for me locally as well.
Is there some issue with the automated tests?

**Comment by ragesoss** [comment]
@ujjwalpathaak it looks like it's related to the update to Chrome 120 on CI, and a tweak the the webdriver config should fix most of those. I'll try to get the tests passing again soon, and then you can rebase.

**Comment by ragesoss** [comment]
@ujjwalpathaak you should be able to rebase it now, I think I've fixed the build.

**Comment by ujjwalpathaak** [comment]
image
this seems to be passing locally for me. I guess this PR is ready for review.

**Comment by ujjwalpathaak** [comment]
@

> image this seems to be passing locally for me. I guess this PR is ready for review.

@ragesoss

**Comment by ragesoss** [comment]
Does this almost mean we no longer need the font files in `app/assets/fonts`? It would be useful to have a more complete explanation of the strategy that you've used for this conversion.

**Comment by ujjwalpathaak** [comment]
There were these icons being used as fonts before -
 -few places used fonts directly embedding them as content from .styl components

.icon-arrow-down:before { content: "\EA01" }
.icon-arrow-up:before { content: "\EA02" }
.icon-arrow:before { content: "\EA03" }
.icon-arrow-reverse:before {
  content: "\EA03";
  position: relative;
  top: 2px;
  transform: rotate(180deg);
  }
.icon-check:before { content: "\EA04" }
.icon-circle_q_mark:before { content: "\EA05" }
.icon-left_arrow:before { content: "\EA06" }
.icon-message:before { content: "\EA07" }
.icon-plus:before { content: "\EA08" }
.icon-restart:before { content: "\EA09" }
.icon-rt_arrow:before { content: "\EA0A" }
.icon-sort:before { content: "\EA0C" }
.icon-trash_can:before { content: "\EA0D" }
.icon-up_arrow:before { content: "\EA0E" }
.icon-wiki-logo:before { content: "\EA0F" }
.icon-z-external-link:before { content: "\EA10" }

- Used SVGs as backgrounds – SVGs were being used as BGs. majorly using the attributes - padding, background-position, background-size; I have used calc() instead of directly using px values as a few times the icons in edu version and non-edu versions were having different locations with the same px values.
- I had to add new SVGs ( same icon with different colors ) as font files were being manipulated by just changing the font color which was not possible while working with SVGs.
  - Example - app/assets/images/circle_q_mark_icons.svg, app/assets/images/circle_q_mark_icons.svg && app/assets/images/circle_q_mark_icons.svg
- Few places i used useState to handle hover effects for the buttons
  - Example - app/assets/javascripts/components/common/AssignCell/AssignButton.jsx
    -  1-2 files which had there hover effects were class-based components so I converted them to functional components
        - Example - app/assets/javascripts/components/students/components/RandomPeerAssignButton.jsx
- Server Components - I just had to change the class names wrt to classes in _icons.style
  - Hover effects are also handled by using .styl components - majorly where there is hover effect in server components. 



**I tried deleting the files -- idts cases are failing -- just one issue if i remove the folder -> ```assets/fonts``` the compilation fails, I think it is related to how the project is being compiled.**

I have not commited the files i deleted but removed their usage in ```_icons.styl```

**Comment by ragesoss** [comment]
I suspect that you can easily fix the compilation by removing a handful of lines from `config.js` and `prepare.js`, the ones that reference `fontsDirectory`. The font files are simply copied to the public directory during the asset build process.

**Comment by ragesoss** [comment]
On the code side this looks good, and it's very promising that the specs are passing.

I'd like this PR to include a more thorough check for UI regressions. I think a good way to to that would be to include a screenshot of each of the icons as it appears in the UI. Many icons are used in multiple places, but just one example of each icon should be fine.

**Comment by ujjwalpathaak** [comment]
**Before**
[Screencast from 06-01-24 12:55:26 AM IST.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/92005669/99a03fab-248b-4f18-b0c1-48f6143c6bd5)
**After**
[Screencast from 06-01-24 12:54:45 AM IST.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/92005669/9389c15f-158e-4935-8783-e8142e0999b6)

I had not added the ```.pull-right``` class with ```.icon-close-small``` class -- so it was not floating to the right. 
Whereas ```.icon-close``` has ```.pull-right``` so they are aligned properly.
Refs - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5564#issuecomment-1879127159

**Comment by ujjwalpathaak** [comment]
**.icon-check
Screenshot from 2024-01-06 17-20-46
.icon-plus-blue
Screenshot from 2024-01-06 17-23-12
.icon-plus
Screenshot from 2024-01-06 17-25-22
.icon-trash_can-hover
Screenshot from 2024-01-06 17-23-05
.icon-trash_can
Screenshot from 2024-01-06 17-22-58
.icon-z-external-link
.icon-z-external-link_white
.tooltip-indicator-heading
Screenshot from 2024-01-06 17-24-37
.tooltip-indicator-list
Screenshot from 2024-01-06 17-24-26
.tooltip-indicator & .tooltip-indicator-hover
Screenshot from 2024-01-06 17-22-15
.icon-rt_arrow_presenter
Screenshot from 2024-01-06 17-28-09
.icon-rt_arrow
Screenshot from 2024-01-06 17-26-06
.icon-rt_arrow_dark
Screenshot from 2024-01-06 17-26-41
.icon-rt_arrow_white_training_all
Screenshot from 2024-01-06 17-26-57
.icon-rt_arrow_white_training
Screenshot from 2024-01-06 17-27-47
.icon-rt_arrow_purple

.icon-rt_arrow_purple_training
Screenshot from 2024-01-06 17-28-48
.sortable-indicator-asc
Screenshot from 2024-01-06 17-31-50
.sortable-indicator-desc
Screenshot from 2024-01-06 17-31-59
.icon-arrow-down_white
.icon-arrow-up & .icon-arrow-down
Screenshot from 2024-01-06 17-40-23
.icon-arrow-up_white
.icon-arrow
.icon-arrow-toggle
Screenshot from 2024-01-06 17-34-03
.icon-arrow-toggle-small
.icon-arrow-reverse-small
.icon-wiki-purple-hover
.icon-wiki-purple
.icon-wiki
.icon-wiki-white
.icon-wiki-white-hamburger
.icon-search
.icon-close-small**

**Comment by ujjwalpathaak** [comment]
**.icon-check
Screenshot from 2024-01-06 17-20-46
.icon-plus-blue
Screenshot from 2024-01-06 17-23-12
.icon-plus
Screenshot from 2024-01-06 17-25-22
.icon-trash_can-hover
Screenshot from 2024-01-06 17-23-05
.icon-trash_can
Screenshot from 2024-01-06 17-22-58
.icon-z-external-link
Screenshot from 2024-01-06 18-11-30
.tooltip-indicator-heading
Screenshot from 2024-01-06 17-24-37
.tooltip-indicator-list
Screenshot from 2024-01-06 17-24-26
.tooltip-indicator & .tooltip-indicator-hover
Screenshot from 2024-01-06 17-22-15
.icon-rt_arrow_presenter
Screenshot from 2024-01-06 17-28-09
.icon-rt_arrow
Screenshot from 2024-01-06 17-26-06
.icon-rt_arrow_dark
Screenshot from 2024-01-06 17-26-41
.icon-rt_arrow_white_training_all
Screenshot from 2024-01-06 17-26-57
.icon-rt_arrow_white_training
Screenshot from 2024-01-06 17-27-47
.icon-rt_arrow_purple
Screenshot from 2024-01-06 17-42-15
.icon-rt_arrow_purple_training
Screenshot from 2024-01-06 17-28-48
.sortable-indicator-asc
Screenshot from 2024-01-06 17-31-50
.sortable-indicator-desc
Screenshot from 2024-01-06 17-31-59
.icon-arrow-up_white
Screenshot from 2024-01-06 18-17-25
.icon-arrow-up & .icon-arrow-down
Screenshot from 2024-01-06 17-40-23
.icon-arrow-down_white
Screenshot from 2024-01-06 18-17-19
.icon-arrow-toggle
Screenshot from 2024-01-06 17-34-03
.icon-arrow-reverse-small
Screenshot from 2024-01-06 18-03-44
.icon-arrow-toggle-small
Screenshot from 2024-01-06 18-03-37
.icon-wiki-purple
Screenshot from 2024-01-06 17-45-37
.icon-wiki
Screenshot from 2024-01-06 17-51-32
.icon-wiki-white
Screenshot from 2024-01-06 17-56-37
.icon-wiki-white-hamburger
Screenshot from 2024-01-06 17-57-36
.icon-search
Screenshot from 2024-01-06 17-45-20
.icon-close-small**
Screenshot from 2024-01-06 17-55-42

**Comment by ragesoss** [comment]
@ujjwalpathaak looks like all the ones in the last comment are private images; they aren't rendering for me.

**Pull request merged**
