### PR TITLE
Fix sandbox training for students

### PR DESCRIPTION
**Pull request by Protonk**
Correct errors in sandbox training, inc:
* Correct article namespace
* Warn students about copying from edit mode

### CODE REVIEW

**Comment by Protonk** [comment]
I can squash if need be, but I'll have to fire up my gh client (just did this in the browser)

**Comment by ragesoss** [comment]
How about: 
 
If you're editing an existing article, a sandbox can be a good place to prepare your first updates by copying a small portion of the article that you want to change or extend. Do not try to overhaul an entire article from the sandbox.

1. Open the original article in **Edit** mode. (References and other templates will break if you copy from **Read** mode.)
2. Select the portion you want to work on — a few paragraphs at most — and copy it.
3. Open your sandbox in Edit mode and paste the copied article content, then save it.
4. Re-enter edit mode in your sandbox, make your changes, and save them.
5. When you're ready to move your small updates back into the article, use the same procedure in reverse: copy from your sandbox in **Edit** mode, and paste the updated content into the article.
  
Once you've gotten the hang of it you can make further edits directly in the article, or repeat the sandbox procedure one portion at a time.

If you're working with a new article that you've created, and doesn't exist on
Wikipedia already, you can "move" your sandbox page into mainspace. In the
next slides, we'll show you how.

**Comment by Protonk** [comment]
I've updated w/ those changes. @ragesoss, do I need to manually wrap the text?

**Comment by ragesoss** [comment]
It parses this yaml file in `|` mode, which means a single linebreak is ignored. So for source code consistency, you can add line breaks. Regardless, wrapping is ultimately done in the browser and doesn't match the source.

**Comment by ragesoss** [comment]
Tweaked format and merged.

**Pull request closed without merging**
