### PR TITLE
upgraded package tinymce to ^6.4.1

### PR DESCRIPTION
**Pull request by kunalthedev**
## What this PR does
Upgraded package [tinymce](https://www.npmjs.com/package/tinymce) to version 6.4.1 which is. To make sure it's working, I edited the code and made the maximum words to 1000, and tried adding more than it and it restricted me. Attached is a video for the same. As well as while creating a course, I've added screenshots of Editor used in replying to open tickets in dashboard.

## Screenshots
image

## Screenrecording
[Screencast from 11-04-23 02:15:57 AM IST.webm](https://user-images.githubusercontent.com/72390769/230995754-4aee0179-47af-4924-8d2b-da888dcd244a.webm)

### CODE REVIEW

**Comment by TheTrio** [comment]
Had a look at the failing tests and I think I know what's going wrong. It looks like this new version depends on some new files which we aren't copying - currently, we only copy skins - see [`prepare.js`](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/76681167f244c9b3949d979614640a9f84740cbf/prepare.js#L34-L36) for details.

I imagine copying over the missing model files from `node_modules` will fix this 404 error.

**Comment by kunalthedev** [comment]
> Had a look at the failing tests and I think I know what's going wrong. It looks like this new version depends on some new files which we aren't copying - currently, we only copy skins - see [`prepare.js`](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/76681167f244c9b3949d979614640a9f84740cbf/prepare.js#L34-L36) for details.
> 
> I imagine copying over the missing model files from `node_modules` will fix this 404 error.

Thanks for the help. Solved now 🫂

**Comment by ragesoss** [comment]
I'm testing this out now, and I see a little "Upgrade" button that links to the TinyMCE marketing site. I guess that didn't show up for you?
upgrade link

**Comment by kunalthedev** [comment]
> I'm testing this out now, and I see a little "Upgrade" button that links to the TinyMCE marketing site. I guess that didn't show up for you? upgrade link

I found this thing in the docs. there is a boolean check by the name `promotion` which is true by default. I've made it to false and now it's not showing.

**Comment by ragesoss** [comment]
That fixed the Upgrade button, but now I'm seeing a layout problem:

editor covers input

Compared to the current version:
old layout

**Comment by kunalthedev** [comment]
> 
It's fine for me. I tested it on different screen sizes and added screenshots below.
Reso 1920X1080
image
Reso 1366x768
image


Can you recheck? Because sometimes changing branches with then running `yarn` because of different package.json in both branches also causes some minor errors

**Pull request closed without merging**
