### PR TITLE
.ajax converted to fetch in course_actions.js 

### PR DESCRIPTION
**Pull request by hardy1334**
In this **.ajax** implementation has been converted to **fetch**  implementation as per issue #2015 in the **course_actions.js**

### CODE REVIEW

**Comment by hardy1334** [comment]
@ragesoss  can u please have a look at it

**Comment by ragesoss** [comment]
@hardy1334 have a look at extra details I just added to the issue description.

**Comment by hardy1334** [comment]
@bwreid  @ragesoss  can u have a look at it

**Comment by ragesoss** [comment]
It looks like the credentials inclusion (which I added details about in the issue description) is still not included.

**Comment by hardy1334** [comment]
@ragesoss  I guess its there in **fetch** function in **api.js** file, as I'm calling fetch function in **course_actions.js**

**Comment by ragesoss** [comment]
I get an error when I use the 'schedule data update' button with this change. (It looks like this particular feature lacks any client-side test, so it got through the test suite anyway.)

**Comment by hardy1334** [comment]
okay,can you guide me a bit how to handle that

**Comment by ragesoss** [comment]
You should be able to recreate the error by going to a course that has a campaign and is already ended, and then clicking 'schedule data update'. The resulting error in the console should give you info to start debugging.

**Comment by hardy1334** [comment]
okay, thanks a lot

**Comment by hardy1334** [comment]
@ragesoss  can u please have a look at this

**Pull request merged**
