### PR TITLE
Improvements in debian setup script #1709

### PR DESCRIPTION
**Pull request by prathamVaidya**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
Improvements in Debian Setup Script. As discussed in Issue #1709.

## Changes

1. Added a fallback package `libmariadb-dev` to support latest debian versions where alternate package `libmariadbclient-dev` was not available by default respositories.
2. Improved Bash Function output_line :  used `%s` formatting over direct concatenation so that special characters like `%` can also be printed without conflicting with formatters.
3. Optimized the execution of MySQL commands by removing the redundant `-p` flag. Since `sudo` is used to execute SQL commands with root privileges, there is no need for the additional `-p` flag, avoiding repetitive password prompts.

## Open questions and concerns

1. Was the `-p` flag in `mysql` command serving any purpose that I missed?
2. Should I also update other os scripts as well?

### CODE REVIEW

**Comment by prathamVaidya** [comment]
@ragesoss can you review?

**Comment by ragesoss** [comment]
LGTM

**Comment by ragesoss** [comment]
The revision importer spec has been very flaky since I updated it to loop through a fairly large set of languages.

**Comment by prathamVaidya** [comment]
Okay, should i fix the same debian script issues for other os script as well? I might not be able to test them but the changes are minimal and should not break anything.

**Comment by ragesoss** [comment]
If you can't test, better to leave them as they are I think.

**Pull request merged**
