### PR TITLE
'No campaign' warning for 'Course' view

### PR DESCRIPTION
**Pull request by takidelfin**
#2150 

Moved some messages to i18n (to make them translatable), added `no-campaign` alert and moved alerts to new `CourseAlert` component.

A new message was written by @ragesoss

GCI Task

screenshot_20181101_122459

### CODE REVIEW

**Comment by ragesoss** [comment]
This looks like it's working as intended! The 'warning' class should not be used; it's basically the same kind of alert that most of the others are: not an error, just informational.

The extraction of the individual alert component is good. As a next step, I think the entire logic for which notification alerts to display should be extracted. That will make it a lot easier to understand both the Course component itself, and the component responsible for all the notifications when you want to add a new one (like this new one).

**Comment by ragesoss** [comment]
This message isn't being rendered:
create timeline message

**Comment by ragesoss** [comment]
I think in `CourseAlert`, the message should be passed as a prop, with explicit I18n done outside of the component. So the interface would look like this:

```jsx
<CourseAlert
  key="submit"
  message={I18n.t('courses.submitted_note')}
/>
```

The way you implemented it works, but it's a little harder to understand the correct usage, because of its reliance on `this.props.children`.

**Comment by ragesoss** [comment]
(I haven't checked the rest of the messages, but if they have similar issues, those will need to be fixed as well.)

**Comment by takidelfin** [comment]
Oh, sorry! initially I wanted pass message using prop, but I thought that
`this.props.children` will look cleaner.

**Comment by takidelfin** [comment]
@ragesoss Could you please review my pull request?

**Pull request merged**
