### PR TITLE
Fix 4466/convert wiki logo to svg and convert new acc btn to functional component

### PR DESCRIPTION
**Pull request by ujjwalpathaak**
Refs #4466 
Refs #5393 

## What this PR does
Changed all icons of wiki-logo being used from font files to SVGs also converted ```/app/assets/javascripts/components/enroll/new_account_button.jsx```
to functional component -- to add hover effect on the button.

## Screenshots
Before:
Screenshot from 2023-12-01 23-30-20
Screenshot from 2023-12-01 20-58-06
Screenshot from 2023-12-01 20-56-01

After:
Screenshot from 2023-12-01 23-19-40
Screenshot from 2023-12-01 23-21-58
Screenshot from 2023-12-01 23-21-51

### CODE REVIEW

**Comment by ragesoss** [comment]
Looks like the icons are a little bigger than before. Can you tweak it to make sure there's as little visual change as possible?

**Comment by ujjwalpathaak** [comment]
Sure i'll push the changes with the next commit

**Comment by ujjwalpathaak** [comment]
image

Should i align this icon? or keep it as it is?

**Comment by ragesoss** [comment]
I think keeping it as it is is best. I vaguely recall that the current positioning was the result of some tweaks to avoid problems for other languages, but I don't remember precisely.

**Comment by ujjwalpathaak** [comment]
Screenshot from 2023-12-02 02-50-38
Screenshot from 2023-12-02 02-50-45

made changes in these two instances *after images

**Pull request merged**
