### PR TITLE
Add rating to articles edited csv

### LINKED ISSUE #2203: Add article rating to the 'Articles edited' CSV data
The CSV of articles edited gets generated by `CourseArticlesCsvBuilder`. Add a new column to include `Article#rating` in the output.

### PR DESCRIPTION
**Pull request by faithngetich**
#### What does this PR do?
Add a CSV header

#### Description of Task to be completed?
Add a rating column to the Edited Articles csv 

#### How should this be manually tested?
- I have not yet been able to figure this out.  
- So far, I have only used my tests to test my work.
This is the command I used to run my test suite.
` rspec spec/lib/analytics/course_articles_csv_builder_spec.rb`
#### What issue does this fix
Fixes #2203 

#### Questions: 
What are the steps to manually test CSV download

### CODE REVIEW

**Comment by ragesoss** [comment]
This looks like it's on the right track.

Looks like this started from an older version of the file, so there's a merge conflict. You should pull in the latest version from upstream, and recommit your changes on top of that: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/git.md

To manually test this, you'll need to create a course that has some edited articles, and then run `RatingImporter.update_all_ratings` (which you can do from a rails console) to import the article ratings. After that, you should be able to click "Download stats" on the course page and then download the article data CSV.

This doc has some instructions for setting up a course with data: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md

If that doesn't have enought of the info you need to successfully test it manually, please let me know.

**Comment by ragesoss** [comment]
Were you able to test this manually, @faithngetich?

**Comment by faithngetich** [comment]
Hey, @ragesoss I have been able to test this out and from what I see, I can see the rating column but the csv file looks a bit odd Here's the screenshot https://www.dropbox.com/s/19okjhnteog5mzr/Screenshot%202018-12-19%2023.54.43.png?dl=0.

**Comment by ragesoss** [comment]
Looks like you didn't have any articles edited by users in the course you tested this with. That user_roles.md doc file has steps for getting some real data into your dev environment.

**Comment by faithngetich** [comment]
@ragesoss here's the latest screenshot of how the csv looks like.
https://www.dropbox.com/s/u8bvulciuijif27/Screenshot%202019-01-02%2020.48.37.png?dl=0

**Pull request merged**
