### PR TITLE
Basic non-en-wiki support

### PR DESCRIPTION
**Pull request by ragesoss**
This needs a corresponding change in the WikiEduDashboardTools endpoint on labs to handle the lang parameter.

### CODE REVIEW

**Comment by ragesoss** [comment]
@adamwight can you take a look and point out any insanity you spot?

**Comment by adamwight** [comment]
This looks like a big improvement!  One small thing that could be TODO is to write a function like Article#get_url, rather than building the URL in various places via string manipulation.

**Comment by ragesoss** [comment]
@adamwight I implemented Course#url, which simplifies things a bit. I'm imagining that if/when we get to the point of wanting to handle multiple language wikis in the same database, we'll want to incoporate the language into the Article table. So in the meantime, pulling it from config should be good enough.

**Comment by ragesoss** [comment]
@ntdb Can you take a look at this and merge it if it looks good to you?

**Comment by ntdb** [comment]
@ragesoss will do this afternoon. I'll take the time to build the change to the tools as well.

**Comment by ragesoss** [comment]
@ntdb thanks much! Be sure to add wiki_language: en to your dev application.yml. (I did that pre-emptively on staging and production.)

**Comment by ntdb** [comment]
Everything is wired up! I don't know how the dashboard should behave using a language value other than 'en' so I'll leave the testing/setup of that to you.

**Comment by ragesoss** [comment]
Thanks @ntdb! I'll give it a spin this weekend to see if it actually works.

**Pull request merged**
