### PR TITLE
[WIP]Change-Subject-field-to-a-multi-select-dropdown-#2499

### PR DESCRIPTION
**Pull request by neozenweb**
Change-Subject-field-to-a-multi-select-dropdown-#2499

Instead of entering subject field as a text, the value can be chosen from a multi-select drop-down. Additionally "Other" values for subjects can be added in the "Other" text field.
image

### CODE REVIEW

**Comment by bwreid** [comment]
@neozenweb Please let us know if you need some help solving this conflict!

**Comment by neozenweb** [comment]
> @neozenweb Please let us know if you need some help solving this conflict!

Thanks @bwreid , I did not realize that there were conflicts because there was no red cross mark at the PR description. I have tried to put in the config.example.yml, and added yarn.lock to my gitignore. Do you think I should add/delete any files from the gitignore?

**Comment by bwreid** [comment]
@neozenweb I think a lot of these issues are stemming from all the changes to the config files. I believe the only changes that should have needed to happen would be in the `app/` folder. It looks like maybe you were having some issues getting the project set up at all. What were the other changes necessary for?

**Comment by neozenweb** [comment]
> @neozenweb I think a lot of these issues are stemming from all the changes to the config files. I believe the only changes that should have needed to happen would be in the `app/` folder. It looks like maybe you were having some issues getting the project set up at all. What were the other changes necessary for?

@bwreid Most or all of the changes except for the app/,  were for the setup. One of them for example in .eslintrc was not recognizing the <end of line> which is different for unix vs windows. Another build failure may be due to the yarn codeclimate-test-reporter dependency which was not included in my package.json as it might be a new addition.  Is there anyway to block out these in .gitignore or what can I do to solve these build errors?

**Comment by bwreid** [comment]
The more sustainable solution is to fix these errors. At the moment, you could just have your PR be the relevant files for the change. That should help in getting the tests to pass and will make it easier to evaluate our code.

Essentially, any changes that are specific to your machine should not be included in this Pull Request.

**Comment by bwreid** [comment]
@neozenweb If I were you, I would try starting a new branch and/or pull request. If you want to keep some of the changes you made to the build, you can do so. Just add the files that are relevant to this PR (e.g. `git add ./app`) and only commit those files. That way we can review your PR and you can continue working on getting the build setup correctly.

**Comment by neozenweb** [comment]
@bwreid I think I will do that. Thanks.

**Comment by neozenweb** [comment]
I have reinstalled the dev on Ubuntu instead of windows, so please delete this pull request. I will do a new PR. Thanks.

**Pull request closed without merging**
