### PR TITLE
Renames home_wiki in article finder functions and corresponding files

### PR DESCRIPTION
**Pull request by Sahethi**
## What this PR does 
Aims to close the issue #4916
Changes were made in `article_finder.jsx` and `article_finder_action.js`

- In `article_finder_action.js`, the name of the variable was `home_wiki` which is not accurate cause it's not always the case that `home_wiki` of the course is passed to it.
- In the case of `article_finder.jsx` where the elements are being rendered, functions are imported from `article_finder_action.js` and here `home_wiki` of courses is passed in `updateFields()` where it refers the same by `this.props.course.home_wiki` and in few functions like `fetchCategoryResults()` & `fetchKeywordResults()`.
- And in cases where updateFields is being passed `wiki`, you can see that it takes its value parameter not based on `courses.home_wiki`

 
## Open questions and concerns
I have renamed `home_wiki` to `wiki` where I thought `home_wiki` of `courses` wasn't being referred to. Please review and let me know.

### CODE REVIEW

**Comment by ragesoss** [comment]
I'm going to hold off on reviewing or merging this until #4905 is finished, so it doesn't cause any conflicts.

**Comment by Sahethi** [comment]
> I'm going to hold off on reviewing or merging this until #4905 is finished, so it doesn't cause any conflicts.

Okay no problem 👍

**Comment by ragesoss** [comment]
@Sahethi okay, it's ready for you to update to reflect the newly merged #4905. :)

**Comment by ragesoss** [comment]
It would be useful to include a note (in the PR description) about where in the code the dividing line is between when it's a home_wiki and when it's just a wiki. As in, where are the places that a course home_wiki actually does get passed to one of these functions?

That will help us think more clearly about whether this change makes sense and why a variable might be `home_wiki` elsewhere but then become just `wiki` when passed to one of these functions.

**Comment by Sahethi** [comment]
Yes, I'll do that @ragesoss

**Comment by Sahethi** [comment]
@ragesoss Heyy, are the changes good enough?

**Pull request merged**
