### PR TITLE
Bundle size analysis

### PR DESCRIPTION
**Pull request by AmitJoki**
Added a webpack config file and modified existing code to be able to generate static bundle analysis from various tools as listed in https://webpack.js.org/guides/code-splitting/

### CODE REVIEW

**Comment by ragesoss** [comment]
What does the output look like, and how do we generate it? (The latter question should be addressed by finding a relevant place in the docs to add details.)

**Comment by AmitJoki** [comment]
@ragesoss I've updated the documentation in the `tools.md` Let me know if that's alright.

**Comment by ragesoss** [comment]
It looks like this bundle analysis config file mirrors a lot of the config code from various gulp/webpack files. Does that mean it's pretty coupled to the build config and will need to be updated a lot as the build config changes?

**Comment by AmitJoki** [comment]
@ragesoss yes. Earlier there was a separate `webpack.config.js` but I guess that's no longer the case. I'll make it so that the gulp/webpack imports the one in the root directory.

**Comment by AmitJoki** [comment]
@ragesoss I have decoupled the config file and the webpack task file. Now, any changes that needs to be done can be made in the `webpack.config.js`

**Comment by ragesoss** [comment]
LGTM. Any concerns about this, @bwreid?

**Comment by bwreid** [comment]
This looks great, and really neat! Thanks for this.  :)

**Pull request merged**
