### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by tnwoodard**
Hi Sage. My name is Tempestt Woodard, and I am a Ruby on Rails Developer and Outreachy applicant. I wanted to say hello and get acquainted with Wikimedia. Here are a few small changes to the manual setup process.

NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
< describe the purpose of this pull request and note the issue it addresses >

## Screenshots
Before:
< add a screenshot of the UI before your change >

After:
< add a screenshot of the UI after your change >
## Open questions and concerns
< anything you learned that you want to share, or questions you're wondering about related to this PR >

### CODE REVIEW

**Comment by ragesoss** [comment]
Thanks! Were you able to get a development environment set up? Would you like an invite to our Slack?

**Comment by tnwoodard** [comment]
> 

Hi Sage. I am almost finished with setting up the development environment. Yes, please invite me to your Slack.  Thanks!

**Comment by ragesoss** [comment]
Great. Let me know your email address. You can send it to sage at
wikiedu.org.

**Comment by tnwoodard** [comment]
Great! I will email you. Thanks.

**Pull request merged**
