### PR TITLE
UI code for selecting namespaces for tracking

### PR DESCRIPTION
**Pull request by vaidehi44**
## What this PR does
The PR contains frontend code for selecting/tracking namespaces for a course.

## Screenshots
image

### CODE REVIEW

**Comment by ragesoss** [comment]
I think this needs a UI message to explain the intended use / effect of Tracked Namespaces... namely, that pages in the tracked namespaces are the ones that contribute to the topline "pages edited", "words added" and similar stats, so you should only track the namespaces that your program is focused on improving.

**Comment by ragesoss** [comment]
On a first survey of the code, this looks good! It's so much easier to see what's going on an why with this smaller PR, versus one that also includes backend changes.

**Comment by vaidehi44** [comment]
> I think this needs a UI message to explain the intended use / effect of Tracked Namespaces... namely, that pages in the tracked namespaces are the ones that contribute to the topline "pages edited", "words added" and similar stats, so you should only track the namespaces that your program is focused on improving.

Okk ... but I didn't get what you meant by **topline** "pages eited"....

**Comment by vaidehi44** [comment]
Also, should the message use tooltip? I guess as this is a new feature, it should be displayed more explicitly.

**Comment by ragesoss** [comment]
I think a tooltip is okay, unless you can think of a better way to do it.

**Pull request closed without merging**
