### PR TITLE
changing subject selector to dropdown in the edit screen (#2499)

### PR DESCRIPTION
**Pull request by jonathan-richer**
## What this PR does
Changed the subject field of the edit screen to the drop down as requested in #2499

## Screenshots
Before:
Screenshot from 2020-05-06 21-20-19

After:
Screenshot from 2020-05-06 21-24-05

## Open questions and concerns
I haven't found anywhere else to change it. I hope this is the right way to do what I intended. I'd love to hear feedback. Thanks !
I believe the custom subjects do not persist, and I would need help about the strategy to accomplish this.

EDIT: Also changed it in the cloned view

### CODE REVIEW

**Comment by jonathan-richer** [comment]
I am not sure at all what failed ...

**Comment by ragesoss** [comment]
Looks like multiple feature specs that involve this 'Edit Details' view are failing because of a JS console error. Are there any errors in your browser console when you use that selector?

**Comment by jonathan-richer** [comment]
Negative, only `same-site` warnings:
Screenshot from 2020-05-06 22-20-48

**Comment by ragesoss** [comment]
@jonathan-richer yes, you can run the specs locally. The failure messages in the build include the command to run that particular test locally: https://travis-ci.org/github/WikiEducationFoundation/WikiEduDashboard/jobs/684109384#L3910

For example, to run only first one that failed: `rspec ./spec/features/admin_role_spec.rb:67`

**Comment by jonathan-richer** [comment]
Thanks, I have run into issues trying this. My active record gem's got corrupted and I thought it was mysql so I created even more issues. So now I'm currently trying to set everything back up

**Comment by jonathan-richer** [comment]
So when I run `rspec ./spec/features/admin_role_spec.rb`, it gives this error:
```
     1.1) Failure/Error: errors = page.driver.browser.manage.logs.get(:browser)
          
          Webdrivers::BrowserNotFound:
            Failed to find Chrome binary.
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chrome_finder.rb:21:in `location'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chrome_finder.rb:10:in `version'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:46:in `browser_version'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:106:in `release_version'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:32:in `latest_version'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/common.rb:135:in `correct_binary?'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/common.rb:91:in `update'
          # /home/joy-ride_soft/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:119:in `block in <top (required)>'
```
Am I missing a gem or am I not running it the right way?

**Comment by jonathan-richer** [comment]
So when I run `rspec ./spec/features/admin_role_spec.rb`, it gives this error:
```
     1.1) Failure/Error: errors = page.driver.browser.manage.logs.get(:browser)
          
          Webdrivers::BrowserNotFound:
            Failed to find Chrome binary.
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chrome_finder.rb:21:in `location'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chrome_finder.rb:10:in `version'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:46:in `browser_version'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:106:in `release_version'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:32:in `latest_version'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/common.rb:135:in `correct_binary?'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/common.rb:91:in `update'
          # ~/.rvm/gems/ruby-2.5.0/gems/webdrivers-4.3.0/lib/webdrivers/chromedriver.rb:119:in `block in <top (required)>'
```
Am I missing a gem or am I not running it the right way?

**Comment by jonathan-richer** [comment]
I can't run the spec, it gives me this error:
```
Webdrivers::BrowserNotFound:
            Failed to find Chrome binary.
```
Even if I did `bundle install --with test` it won't download the Chrome drivers.

**Comment by ragesoss** [comment]
Hmm... so it looks like you have `webdrivers` installed, but it's the actually Chrome binary that isn't being found. I assume you have Chrome on your system already? If not, I think it will work after you install Chrome. If so, it seems that the Chrome binary just isn't where webdrivers is looking for it; that's not an issue I've seen before.

**Comment by jonathan-richer** [comment]
I've been working on fixing the issue the whole weekend, until I went directly to the WebDrivers gem repository to learn that all I had to do is `export WD_CHROME=/path/to/driver`, for future reference, the gem looks for the WD_CHROME environment variable or the default location (which is listed by platform on their wiki). But now when I run the specs, I just don't get any output and it takes such an enormous amount of time. Also I'd like to know if there's a more instantaneous messaging software, I think I've seen Slack in an issue but I'm not sure. I would appreciate to be part of this.

**Comment by ragesoss** [comment]
No output at all, not even a series of dots (each of which indicate a test that just passed)?

Send me an email to sage at wikiedu.org and I'll get you a Slack invite.

**Comment by jonathan-richer** [comment]
After trying it again a few times, it now throws this error:
`ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes`.
And at the end it says `Failure/Error: ActiveRecord::Migration.maintain_test_schema!`

**Comment by ragesoss** [comment]
Slack invite sent.

That's an interesting error. We've done some recent migrations that result in changing the length of index keys (ie, moving to UTFMB4 encoding for some data). It sounds like your test database is out of sync with what the schema.rb file expects.

I suggest resetting the test database for the test environment.

**Comment by jonathan-richer** [comment]
Crazy how destructive 7 characters are ...

**Comment by jonathan-richer** [comment]
Any reviews yet?

**Comment by ragesoss** [comment]
Sorry, it's been a rather hectic week. I will try to review this early next week. Thank you for the ping.

**Comment by jonathan-richer** [comment]
Absolutely no problem

**Comment by ragesoss** [comment]
This is close, but I think the 'use a different value by typing it in' option is not as discoverable as it should be. The input should be clearable, and when it's clear, there should be placeholder text like "Type or choose from the list...".

I think the label "create <input>" when you type in your own value is also confusing. Maybe if it was instead "Custom value: <input>"?

I'm not sure how much of this is configurable with react-select, but at least some of it is.

**Pull request closed without merging**
