### PR TITLE
Alert option added when Instructors change details of programs which have expired

### PR DESCRIPTION
**Pull request by hardy1334**
Earlier,when a course date has expired, if instructors change details of expired course, they were not given any alert that <b>they can create a new program</b>.

<b>Now:</b>
When Instructors change details of expired course they are given alert everytime they do any change in the <b>expired course</b>

screenshot from 2019-01-28 19-35-44

### CODE REVIEW

**Comment by hardy1334** [comment]
#2384

**Comment by hardy1334** [comment]
#2384

**Comment by hardy1334** [comment]
Now, **create new course** link is given to the user in the program.<br><br>
screenshot from 2019-02-10 19-32-35

**Comment by hardy1334** [comment]
@ragesoss please can you have a look at it

**Comment by ragesoss** [comment]
It looks like this unconditionally adds a link the the 'Details' section to create a new course. The idea with the issue is to give a warning to the user in a very specific situation only. I'll update it to clarify.

**Comment by hardy1334** [comment]
@ragesoss  This warning is shown if the current date exceeds the **Activity tracking end** time

screenshot from 2019-02-14 00-47-14

**Pull request closed without merging**
