### PR TITLE
fixes create campaign passcode behaviour 

### LINKED ISSUE #1613: Campaign Default Passcode text field should hide after clicking another option
At creating a new Campaign, when clicking on "Customize passcode" a text field to enter a Default Passcode appears. This text should be hidden again after clicking on another option (Random Passcode or No Passcode), to not generate confusion to the users.

Note: This behaviour is generated by Jquery at assets/javascripts/campaigns.js so it probably should be fixed by changing the Jquery there.

### PR DESCRIPTION
**Pull request by psinghal20**
Fixes #1613.
The issue was because the onchange function is not called when other radio buttons were selected.
Solution: Added a common class to all the radio buttons and applied the onchange function to this class and check with the custom radio buttons value.

### CODE REVIEW

**Comment by psinghal20** [comment]
Hi @ragesoss @mauditecandela , Please review this PR and please help me with travis-ci build failure.

**Comment by ragesoss** [comment]
@mauditecandela can you review this and test it out? I'll merge it once I get the okay from you.

**Comment by ragesoss** [comment]
@psinghal20 build failure was a random travis failure during dependency installation. I passed when I restarted the build.

**Comment by mauditecandela** [comment]
@ragesoss all fine from my side. It can be merged :)

**Pull request merged**
