### PR TITLE
[WIP]: Issue #2520

### LINKED ISSUE #2520: Change passcode detail to be a link
image

Most instructors don't need the passcode as much as they need the actual link to send out to students to enroll. When the details section is _not_ being edited, we should change the passcode from plain text to actually being the enrollment link. When editing, the regular fields should still show.

### PR DESCRIPTION
**Pull request by twisted-sres**
Fixes #2520 
screenshot from 2019-03-04 00-23-41

### CODE REVIEW

**Comment by twisted-sres** [comment]
screenshot from 2019-03-04 00-23-41
Hey, I think, there is some problem in fetching the URL of the page as it says undefined, but let me know if I am on the right page.
Also, now that we are showing the course link in the passcode, I was wondering if we still need to show the same in the notification.

**Comment by twisted-sres** [comment]
@bwreid please review

**Comment by ragesoss** [comment]
@twisted-sres please have a look at the travis-ci build log; the tests are failing, with the immediate cause being the eslint errors in details.jsx.

**Comment by twisted-sres** [comment]
Is there a way to fix these errors automatically, like running gulp with --fix flag?

**Comment by bwreid** [comment]
@twisted-sres You can run the following in the project directory on the file(s) you've changed.
```
./node_modules/.bin/eslint --fix ./path/to/file
```

Additionally, is the change for `yarn.lock` needed?

**Pull request closed without merging**
