### PR TITLE
Upgrade jeet to 7.2.0

### LINKED ISSUE #2059: Upgrade Jeet to version 7
We currently use Jeet 6.x to provide grid layouts in our CSS. Upgrading to the latest version will require some changes: the location of the files we need to import is different, and some of the functions that jeet provides are used in various stylesheets and need to be renamed (`cf()`, at least).

Migration guide: https://github.com/mojotech/jeet/wiki/Migrating-from-6-to-7

### PR DESCRIPTION
**Pull request by aSquare14**
fixes #2059

### CODE REVIEW

**Comment by aSquare14** [comment]
@ragesoss This says that for styl files. Path is same. https://github.com/mojotech/jeet/wiki/Migrating-from-6-to-7#700-removes-superfluous-directories-and-renames-jeetscss-and-jeetstyl-to-indexscss-and-indexstyl

Travis CI is showing that it cannot import jeet

**Comment by ragesoss** [comment]
I don't think that bit of the documentation is correct, as the file looks like it's at `index.styl` instead of `jeet.styl`: https://github.com/mojotech/jeet/tree/master/styl

**Comment by aSquare14** [comment]
How can I reproduce this failing test on my local machine ? Running gulp build or yarn run build passes for me.

**Comment by ragesoss** [comment]
Hmm... I don't know. `gulp build` is the same thing that runs on CI, so I would expect the same error to show up for you locally.

**Comment by aSquare14** [comment]
It doesn't !

**Comment by ragesoss** [comment]
I'll take a look at it soon to see if I can figure it out.

**Comment by aSquare14** [comment]
Thanks !

**Comment by ragesoss** [comment]
I do get those same errors locally.

I had to change the import paths to `node_modules/jeet/styl` to fix them.

**Comment by ragesoss** [comment]
However, while the CSS compiles with that change, the grid layout isn't working:

no grid

What output do you get when you run `yarn`? I can't figure out why this would work locally for you without changing the `@import` paths in `training.styl` and `_shared.styl`, unless you still have the old version of jeet in your `node_modules` directory.

**Comment by aSquare14** [comment]
I'll work on it . Thanks for testing it out !

**Pull request closed without merging**
