### PR TITLE
transfer i18n-js export task from gulp to webpack

### PR DESCRIPTION
**Pull request by pv-912**
## What this PR does
Remove the i18n-js export task from the gulp pipeline and add it to the webpack which will execute it before build start.

### CODE REVIEW

**Comment by ragesoss** [comment]
Cool! Looks like the build is passing. I'm dubious about WebpackShellPlugin, though. It hasn't been updated in 3 years and people are forking it to fix bugs. Is there a reason this plugin in needed instead of using a built-in option for running a shell task like `child_process`?

Is there an issue for this? Does it get us closer to a solution for #1940 ?

**Comment by pv-912** [comment]
> Is there a reason this plugin in needed instead of using a built-in option for running a shell task like `child_process`?

I will try to do it using `child_process`. Also, I have found a way to this on [stackoverfolw](https://stackoverflow.com/a/49786887/8111649) and will try that.

**Comment by pv-912** [comment]
@ragesoss However `webpackShellPlugin` also does the same thing as we can see [here](https://github.com/1337programming/webpack-shell-plugin/blob/master/src/webpack-shell-plugin.js) like uses the `child_process` and executes it before or after the build started.

**Comment by ragesoss** [comment]
If it's the same thing and can be done with a built-in node command, I'd rather avoid adding an abandoned dependency.

**Comment by ragesoss** [comment]
This is now taken care of in `prepare.js`.

**Pull request closed without merging**
