### PR TITLE
FIXED : Trailing whitespace in i18n messages

### PR DESCRIPTION
**Pull request by shailesh1028**
As per the error defined in the issue: Trailing whitespace in i18n messages #4332, I have made some changes in config/locales/en.yml.
Earlier                                 Now
'Campaigns: '        |        'Campaigns:'                          
'Predicted rating for the article is:  | 'Predicted rating for the article is:'
'Tags: '                   |           'Tags:'                               
'Campaigns: '        |        'Campaigns:'                          
'To get started, '    |       'To get started,'                     
' or '                       |           'or'                                 
'Passcode: '          |        'Passcode:'                           
'Edits by: '             |         'Edits by:'                           
'Assigned: '           |         'Assigned:'                           
'Reviewing: '         |         'Reviewing:'  
Please review the changes.

### CODE REVIEW

**Comment by ragesoss** [comment]
This removes the whitespace, but it will make these places in the UI appear without necessary whitespace now. For example, The passcode listing in the Details box will say `Passcode:abcde` instead of `Passcode: abdce`.

In addition to changing the en.yml, we'll need to find where each of those messages are used and update the components to render appropriately without relying on trailing whitespace in the i18n message itself.

**Comment by shailesh1028** [comment]
Basically, the whitespace should not be contained in the message but it should be present while rendering the components. Passcode:abcde should look like Passcode: abcde.[message: value]. This means that the whitespace should be there in the value part depending on whether the value is empty or not. So I have to refactor it where the messages are used in the components. Am I right?
Or do I need to remove the whitespace in the message itself, wherever they are used ... say in language.js files present in public/asset/javascript/i18n files
Please let me know !!

**Comment by ragesoss** [comment]
Yes, refactor how the messages are used in components. The i18n js files in
public/assets are generated from the yml locale files, and shouldn't be
edited directly. (They also are not under version control.)

**Comment by shailesh1028** [comment]
Hi @rageross, I got delayed by an uncalled event. Now I have edited the components such that [message: value] will be shown. But I had one doubt i.e in case if the value is empty then it should show [message: ] or [message:]. 
should a single space be shown if the field is empty?
Or do I need to add a condition in rendering the components if the values are empty? 
I feel that some of the above values won't be empty eg: Passcode, Assigned, Reviewing.
Please guide me !! Thanks

**Comment by ragesoss** [comment]
If the value is empty, then it doesn't matter whether the single space is included or not. These should all be implemented so that they work if the value is empty. At least some of them, like passcode, are sometimes empty.

**Comment by ragesoss** [comment]
Sorry, I missed that you updated this @shailesh1028. Looks like there's one failing test related to your change, and it's a case where there was not any whitespace previously (I think).

If you update the spec, I think that should be fine.

It looks like this changes 10 messages, but it only changes 6 places in the frontend where messages are used. Are there more components that need to be updated?

**Comment by shailesh1028** [comment]
@ragesoss  I have made the changes in the frontend for the following messages:
1) 'Predicted rating for the article is: | 'Predicted rating for the article is:'
2) 'To get started, ' | 'To get started,'
3) ' or ' | 'or'
4) 'Passcode: ' | 'Passcode:'
5)'Edits by: ' | 'Edits by:'
6)'Assigned: ' | 'Assigned:'
7) 'Reviewing: ' | 'Reviewing:'
6 and 7 had been rendered by a common element, so it counts for one change. This is how only 6 changes were visible in the code.
Apart from these changes, for the remaining parts, the code already took care of the whitespace problem. No need to add more whitespace in those cases.
I hope this explains your doubt. Please review it.

**Comment by ragesoss** [comment]
@shailesh1028 thanks, that's helpful! Can you update the failing spec?

**Comment by shailesh1028** [comment]
@ragesoss  Do you want me to resolve the errors occurring during the build of Travis-CI?
If so, then I have checked and it's occurring because of this eslint-loader package. I checked we are using "eslint-loader": "^4.0.2" and "babel-eslint": "^10.1.0" which are good enough to use. 
I checked the lines at which it is throwing errors, and those lines of code are not connected with the changes I did. I could not understand why it failed. Could you help me out?

**Comment by ragesoss** [comment]
I'm referring to this spec which is failing because of a (minor) change introduced in this PR: https://travis-ci.org/github/WikiEducationFoundation/WikiEduDashboard/jobs/759100319#L3025

It's a feature spec that looks for a specific string, and now that string has a whitespace difference, causing the spec to fail.

**Comment by shailesh1028** [comment]
@ragesoss  I did as per what you explained. The build is also working fine. Please review it.

**Pull request merged**
