### PR TITLE
Makes a popover in a modal responsive.

### PR DESCRIPTION
**Pull request by codingmamakaz**
## What this PR does
Makes a popover in a modal responsive.

## Screenshots 
Before:

Screen Shot 2019-10-06 at 11 14 23 AM

After:

Screen Shot 2019-10-06 at 11 14 54 AM
Screen Shot 2019-10-06 at 11 15 13 AM

## Open questions and concerns
Hi! I pushed a PR earlier and realized I added schema file with my commit. I created another PR to keep things clean. This is my first PR. Rspec is not passing, but all I touched was CSS, so I'm assuming I can ignore it. Npm tests are passing. I will appreciate any feedback!

### CODE REVIEW

**Comment by ragesoss** [comment]
Thanks! It looks like this is headed in the right direction.

The "+" button looks like it gets shifted to the next line on the left, in the 'after' screenshot, and the arrow that is supposed to connect the popover to the "+" button isn't lined up with that button.

Also, there's still a schema.rb change included in this PR. This is basically a benign change, since the schema.rb gets regenerated from your local database whenever you run migrations but the format and defaults can change between Rails versions and/or based on the local database environment. But it should not be included in the PR. What I usually do is `git stash` immediately after running migrations, unless I'm working on something that is supposed to change the schema.

**Comment by ragesoss** [comment]
The easiest way, since there are just a few changes, will be to make a new branch from `master`, then copy back in the stylesheet changes and make anew commit with just those.

**Comment by codingmamakaz** [comment]
@ragesoss Would this work?

Full screen
Screen Shot 2019-10-07 at 3 16 54 PM

Width 1270
Screen Shot 2019-10-07 at 3 17 04 PM

Mobile
Screen Shot 2019-10-07 at 3 16 29 PM

**Comment by codingmamakaz** [comment]
I started a new branch,, so it does not include the schema this time. I will open a new PR and close this one if these changes work.

**Comment by ragesoss** [comment]
The latest screenshots look good. Is that username icon something your browser adds? I've never seen that before.

**Comment by codingmamakaz** [comment]
It must be. I didn't add any in the code. Okay, I will open a new PR with the new changes.

**Pull request closed without merging**
