### PR TITLE
added github actions test 1

### PR DESCRIPTION
**Pull request by aaditya9899**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
< describe the purpose of this pull request and note the issue it addresses >

## Screenshots
Before:
< add a screenshot of the UI before your change >

After:
< add a screenshot of the UI after your change >
## Open questions and concerns
< anything you learned that you want to share, or questions you're wondering about related to this PR >

### CODE REVIEW

**Comment by ragesoss** [comment]
Any further progress on this, @aaditya9899 ?

**Comment by aaditya9899** [comment]
> Any further progress on this, @aaditya9899 ?

yes @ragesoss  i got busy in my exams but now I am continuing it from today and if not able to solve it within this week , you can hand it over to someone else but i will try my best as this was my first experience in this tech and few things are left to fix it now.

**Comment by ragesoss** [comment]
Sounds great. Thanks for the update!

**Comment by aaditya9899** [comment]
Thank you in fact , i should have given the update beforehand , won't happen again.

**Pull request closed without merging**
