### PR TITLE
Change passcode detail to be a link

### PR DESCRIPTION
**Pull request by puthalalitha**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
Changed passcode detail to be a link

## Screenshots
Screen Shot 2019-12-02 at 8 04 38 PM

After:
Screen Shot 2019-12-02 at 7 08 11 PM

### CODE REVIEW

**Comment by ragesoss** [comment]
I think this will be most useful if we keep the same format, and just change the passcode itself into a link.

So it should still say something like "Passcode: abcdef", but with the "abcdef" part done as a link.

**Comment by puthalalitha** [comment]
Changed the passcode itself into a link. Now it is showing "Passcode: mcbevngo". and "mcbevngo" as a   link.
Screen Shot 2019-12-04 at 6 24 55 AM

**Comment by ragesoss** [comment]
From the build failure, it looks like there is a problem related to editing the passcode. A feature spec related to passcodes is failing; it could indicate a real problem, or it could be a test that needs to be adjusted for the new behavior.

**Comment by ragesoss** [comment]
I merged the other PR that address this issue.

**Comment by puthalalitha** [comment]
Ok, no problem. The other one is pretty  good. I saw that code and it is impressing.

**Pull request closed without merging**
