### PR TITLE
add modal to view articles tracked by a category

### PR DESCRIPTION
**Pull request by TheTrio**
Looks like

SCR-20230825-qcsg

### CODE REVIEW

**Comment by ragesoss** [comment]
This is throwing a warning:

```
instrument.js:109 Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>.
    at div
    at eval (webpack-internal:///./node_modules/create-react-class/factory.js:897:37)
    at ArticleTitlesModal (webpack-internal:///./app/assets/javascripts/components/categories/article_titles_modal.jsx:54:27)
    at Category (webpack-internal:///./app/assets/javascripts/components/categories/category.jsx:39:21)
    at tbody
    at table
    at div
    at eval (webpack-internal:///./node_modules/create-react-class/factory.js:897:37)
    at div
    at CategoryList (webpack-internal:///./app/assets/javascripts/components/categories/category_list.jsx:31:21)
    at CategoryHandler (webpack-internal:///./app/assets/javascripts/components/categories/category_handler.jsx:27:21)
    at div
    at eval (webpack-internal:///./node_modules/create-react-class/factory.js:897:37)
    at ComponentWithRouterProp (webpack-internal:///./app/assets/javascripts/components/util/withRouter.jsx:31:81)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:234:68)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
    at div
    at div
    at eval (webpack-internal:///./node_modules/create-react-class/factory.js:897:37)
    at ComponentWithRouterProp (webpack-internal:///./app/assets/javascripts/components/util/withRouter.jsx:31:81)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:234:68)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
    at Suspense
    at routes (webpack-internal:///./app/assets/javascripts/components/util/routes.jsx:96:79)
    at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/index.js:119:5)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:19:20)
    at Main
```

**Comment by ragesoss** [comment]
I think it would help to include the title of the displayed category (or the PSID) in the header of the modal.

**Comment by TheTrio** [comment]
Fixed that DOM issue and added the category title to the heading of the modal

**Comment by ragesoss** [comment]
Looks good. I'm going to merge now.

One minor improvement would be to *not* scroll to the top of the page when the modal opens. If you have multiple categories, plus a list of edited articles, you have to scroll down each time to reach the categories if you want to view more than one.

**Pull request merged**
