### PR TITLE
add ref to diff, resize empty diff col, wrap Loading element in tbody, rename certain react components UNSAFE_

### PR DESCRIPTION
**Pull request by dnahol**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does

- Address issue  #1088 Diff Viewer shows only one column, on left, if all changes are new paragraphs 
- Fixes a bug within the diff table

Files changed: 
app/assets/javascripts/components/revisions/diff_viewer.jsx
- Add ref to diff:
  The Dangerously Set HTML from the Wikipedia Diff URL did not previously have a ref. I added one, including a setDiff method for it.

- Resize empty diff column: 
  When the table cells, td elements, are empty, they previously lost their width. This is what was causing issue #1088. This PR sets the first empty cell to 50% width in the table, so that both (-) and (+) columns can take up half the table width.

- Wrap Loading and (-) diff marker elements in tbody:
  There were previously errors caused by the <Loading/> and (-) diff marker elements because they were within a table without being wrapped in tbody. This PR wraps both in tbody, tr, and td, fixing the errors.

## Screenshots
Before:
Screen Shot 2019-11-05 at 6 39 10 AM

After:
Screen Shot 2019-11-08 at 10 27 33 PM

## Open questions and concerns
I learned how to use dangerouslySetInnerHTML in React, how to add refs to elements using JSX in React components, and that divs within tables must be wrapped in a tbody, tr, and td.

### CODE REVIEW

**Comment by khyatisoneji** [comment]
I tested it out, it works smoothly, great work!

**Comment by khyatisoneji** [comment]
As mentioned by @ragesoss, it still gives the warning to convert components( like componentWillMount, componentWillReceiveProps) to use new lifecycle methods

Let us know if you need any help

**Comment by dnahol** [comment]
Hey @khyatisoneji, thanks for looking it over. I looked at the errors and the React documentation. I tried changing `componentWillReceiveProps` in `app/assets/javascripts/components/revisions/diff-viewer.jsx` to `componentDidUpdate` and I am left with diffs that won't load. I tried the same for `app/assets/javascripts/components/common/article-viewer.jsx` with the same result.

I think that properly updating all the soon-to-be-deprecated `componentWillMount` and `componentWillReceiveProps` methods is going to be a separate refactoring using the new React version way of doing things. 

What do you think about me opening a second issue to work on this?

In the meantime, I ran this command from the documentation to rename such methods in `app/assets/javascripts`:

`npx react-codemod rename-unsafe-lifecycles` 

`componentWillReceiveProps()` -> `UNSAFE_componentWillReceiveProps()`
`componentWillMount()` -> `UNSAFE_componentWillMount()`

**Comment by khyatisoneji** [comment]
You can open another PR to remove all warnings, this PR would only involve changing only a few files
(article_handler.jsx, article_finder.jsx, nav.jsx, diff_viewer.jsx, article_viewer.jsx)

**Comment by khyatisoneji** [comment]
The errors would be shown in the terminal(only for frontend code), or you can run tests locally to check for any errors

**Comment by dnahol** [comment]
Hi @khyatisoneji. Thank you, I hadn't noticed the linter errors- I think I created them by running `npx react-codemod rename-unsafe-lifecycles` in my previous commit to fix the React lifecycle warnings. 

I fixed the 18 linter errors and squashed the commit.

**Comment by ragesoss** [comment]
Cool! This looks like a nice improvement. I'm going to merge it now.

One way to improve it a little more will be to handle the Loading state better. After this change, the loading animation includes a border, which is a little distracting. Ideally, the loading animation should span the entire DiffViewer element instead of just the left portion.

**Comment by dnahol** [comment]
Hey @ragesoss I see what you mean. I tried a couple of things- no luck yet. I'll open a separate issue to deal with this.

**Pull request merged**
