### PR TITLE
Add a warning notification on trainings when not logged in

### LINKED ISSUE #733: When logged out, users taking the training should see a message about their logged-out status
Some students may be going through training while logged out, and then not receiving credit for it.

The interface should make it obvious to a logged out user that they are viewing the training while logged out and will not receive credit for completing it unless they log in.

### PR DESCRIPTION
**Pull request by ragesoss**
Resolves #733

### CODE REVIEW

**Comment by ragesoss** [comment]
@thenickcox Help! I broke a javascript test that I don't understand.

**Comment by thenickcox** [comment]
@ragesoss https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/750/commits/7df581b02b43d8114e232ae61f779e490115b2df

Our test dom didn't have a `main` element.

**Comment by bmathews** [comment]
It can also be stubbed per test by doing:

```
TestMenu = ReactTestUtils.renderIntoDocument(
  <div id="main" data-user-id="3">
    <TrainingSlideHandler
      loading=false
      params={params}>
      <SlideMenu params={params} />
    </TrainingSlideHandler>
  </div>
)

```

**Comment by ragesoss** [comment]
Merged directly already.

**Pull request closed without merging**
