### PR TITLE
React reduxv6#2559

### PR DESCRIPTION
**Pull request by hjhimanshu01**
## What this PR does [WIP]
Upgrades react-redux version to v6 form current version

## Concerns

- As of now react-redux v6 has made changes that have particularly affected the import "shallow" from enzyme module

``` 
const wrapper = shallow(
   <Provider store={store}><Component /></Provider>
```
above snippet will return an error as shallow renders the topmost component that is render , so as a way to bypass that , I have introduced a `createDecoratedEnzyme` function to include store in the component , please have a look at that , createContext also referred but of not much use here as rendering through shallow will again result an error. 

## For Future

As of now , there are talks of passing store similar to react-redux v5 as it is an open issue on react-redux github repository , that will probably make v6 backward compatible .

### CODE REVIEW

**Comment by hjhimanshu01** [comment]
Hey , I just got an update about react-redux v7 . Check this out!
    Link : https://github.com/reduxjs/react-redux/issues/1177#issuecomment-473742889

**Comment by hjhimanshu01** [comment]
@bwreid ,  could you have a look at this , I'm facing a little difficulty here .

**Comment by bwreid** [comment]
@hjhimanshu01 I think the following should fix the one failing test.

```js
const wrapper = decoratedShallow(
      <SettingsHandler context={store} />
    );
    const container = wrapper.dive();
```

Are there really no changes needed to the rest of the application? 😱 I'm clicking around on the app and things seem to be working fine. But it might be worth another quick sweep of the change documentation.

Thanks for working on this!

**Comment by hjhimanshu01** [comment]
@bwreid ,Thanks! :) , also I think decoratedShallow already has store passed to it , so basically it does have a store configured and passing context won't work , exception raised :
`    TypeError: ShallowWrapper::dive() can only be called on components
`

**Comment by bwreid** [comment]
@hjhimanshu01 Sorry, where are you seeing this error? In relation to what file?

**Comment by hjhimanshu01** [comment]
@bwreid , No worries! :) , I'm geting error in this file test/components/settings/settings_handler.spec.jsx

**Comment by bwreid** [comment]
Ah, I see. So you should just be able to remove the store from SettingsHandler then.
```js
const wrapper = decoratedShallow(
  <SettingsHandler />
);
const container = wrapper.dive();
```

**Comment by hjhimanshu01** [comment]
Still error persists , apparently it says that can't pass store to the props , but I had used the same in settings/add_admin_form.spex.jsx

here's the log :
```
Invariant Violation: Passing redux store in props has been removed and does not do anything. To use a custom Redux store for specific components,  create a custom React context with React.createContext(), and pass the context object to React-Redux's Provider and specific components like:  <Provider context={MyContext}><ConnectedComponent context={MyContext} /></Provider>. You may also pass a {context : MyContext} option to connect
```

I do think it's due to import of `SettingsHandler` component as SettingsHandler has a store configured using connect.

**Comment by ragesoss** [comment]
@bwreid this seems okay to me. Is there anything else you wanted to see from this before we merge?

**Comment by bwreid** [comment]
@ragesoss Now that the tests are passing, nope! I'll merge it.

**Pull request merged**
