### PR TITLE
Fix 4466/convert arrow icons to svgs

### PR DESCRIPTION
**Pull request by ujjwalpathaak**
## What this PR does
Hello @ragesoss,
I was working to change all the arrow icons to SVGs, I have added few of the screenshots.
I was facing a problem for these pages - 
```http://localhost:3000/training/students/wikipedia-essentials```
image

I am not able to find the ```.jsx``` component for this button, after toggling a bit in React DevTools -- I guess this page is not being rendered in react? How can I access this element?

## Screenshots
Screenshot from 2023-12-02 19-28-16
Screenshot from 2023-12-02 19-29-14
Screenshot from 2023-12-02 20-35-47
Screenshot from 2023-12-03 22-14-08

### CODE REVIEW

**Comment by ragesoss** [comment]
You are correct, that page is not rendered in React (or least, not all of it). The example you show is rendered server-side with `app/views/training/training_module.html.haml`. The button classes are defined in `TrainingModulePresenter`. If you need more details about how the server-side code works leading up to rendering that page, let me know and I can give a brief outline of the code flow.

**Comment by ujjwalpathaak** [comment]
I was able navigated through the ```.haml``` files. I will review all the changes and make a few adjustments. Afterward, I think the PL would be ready to be reviewed.

**Comment by ujjwalpathaak** [comment]
@ragesoss I think the PL is ready to be reviewed
### Before
Screenshot from 2023-12-06 19-31-21
Screenshot from 2023-12-06 19-32-31
Screenshot from 2023-12-06 19-35-06
Screenshot from 2023-12-06 19-36-58
Screenshot from 2023-12-06 19-37-16
Screenshot from 2023-12-06 19-37-59
Screenshot from 2023-12-06 19-44-06
Screenshot from 2023-12-06 19-53-05
Screenshot from 2023-12-06 19-55-48
Screenshot from 2023-12-06 20-01-02

### After
Screenshot from 2023-12-06 19-31-27
Screenshot from 2023-12-06 19-32-39
Screenshot from 2023-12-06 19-35-23
Screenshot from 2023-12-06 19-37-03
Screenshot from 2023-12-06 19-37-22
Screenshot from 2023-12-06 19-38-07
Screenshot from 2023-12-06 19-44-12
Screenshot from 2023-12-06 19-54-00
Screenshot from 2023-12-06 19-56-54
Screenshot from 2023-12-06 20-08-34

**Comment by ujjwalpathaak** [comment]
it is failing for ```revision_score_importer_spec.rb```

**Comment by Brajesh1213** [comment]
may I contribute to this bug?

**Comment by ragesoss** [comment]
> may I contribute to this bug?

This one also has an open PR that I have not yet reviewed, and is probably already taken care of.

**Pull request closed without merging**
