### PR TITLE
Articles tab show's more detail about each article

### PR DESCRIPTION
**Pull request by testa19**
Changes for enhancement https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1360

Campaign.articles_courses relation is added
campaigns/articles view changed to show table header row and two additional info columns
Sorting articles option is added to javascript

### CODE REVIEW

**Comment by ragesoss** [comment]
Nicely done! One last tweak that would improve it a bit more would be to add sorting by wiki (the last column). @testa19 let me know if you want to add that now; otherwise, I'll merge it as-is.

**Comment by testa19** [comment]
@ragesoss ok, let me take a quick look (i don't know how to modify a PR with another commit yet)

**Comment by ragesoss** [comment]
@testa19 you just checkout your branch again, add a new commit, and push it. The PR will update automatically.

**Comment by testa19** [comment]
@ragesoss There is an issue with column name: there is no translation for it

**Comment by ragesoss** [comment]
@testa19 you can add one by editing `config/locales/en.yml`.

**Comment by testa19** [comment]
@ragesoss So i can just add `wiki_language` field to `articles` "model"?

**Comment by ragesoss** [comment]
@testa19 in this case, the column is both the wiki language and project (like `en.wikipedia`), so just 'wiki' is probably the best name for it.

**Comment by testa19** [comment]
@ragesoss Ok, seems like the second commit has been checked:
Wiki column name and sorting were added
.table--expandable CSS class was removed from the table (nothing to expand on)

**Pull request merged**
