### PR TITLE
Refactored article_finder.jsx to Functional Component

### PR DESCRIPTION
**Pull request by om-chauhan1**
Refactored Article Finder from class component to functional component.

For Article Finder 
Before:
[Before.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/b6214919-ad36-4f25-bcc7-84fa2b647b39)

After:
[After.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/f2954ea1-11bc-4992-bcfd-09860ec5008e)

### CODE REVIEW

**Comment by om-chauhan1** [comment]
@ragesoss Kindly guide me fixing this error due to which this CI / build test is failing.

**Comment by ragesoss** [comment]
Hmmm... it's the article finder spec that is failing, so you should check whether that spec passes locally for you. I'll re-run CI just in case it was simply a flaky test unrelated to your change.

**Comment by om-chauhan1** [comment]
@ragesoss  I tried running yarn test locally and all the 36 test suites of 204 tests passed successfully.
Here, is the video of the same.

[All Test Passed.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/5eb42105-4cd6-4079-a1f6-58418d33d207)

**Comment by ragesoss** [comment]
@om-chauhan1 `yarn test` only executes the javascript tests. The failing test is one of the browser-based Feature specs from the Ruby `rspec` test suite.

**Pull request merged**
