### PR TITLE
Use AlertsList React component in /alerts_list (try #2)

### PR DESCRIPTION
**Pull request by chrisnorwood**
## What this PR does
fix for #1803 

* Refactors AlertsList component into seperate CampaignAlerts and AdminAlerts components with shared functionality
* Allows for asynchronous 'resolving' for AdminAlerts
* Campaign alerts functionality not changed
* Sort options are determined from alerts that are actually available to sort

## Screenshots
Before:
1803-before

After:
1803-after-NEW

## Open questions and concerns
Note 1: CampaignAlerts and AdminAlerts both still using `UNSAFE_componentWillMount` instead of `componentDidMount`.  I attempted the switch, and I found out the MultiSelectField component would break when given its default values from a Redux state that was dispatched in "DidMount" instead of a "WillMount".  As numerous other components rely on MultiSelectField, I think this is better solved in another issue/PR.

Note 2: @ragesoss : You suggested earlier today that the admin view _could_ use the AlertType names instead of the "friendly" versions.  In this PR, both campaign and admin alert lists use the friendly name, as computed in the `transformAlertsIntoOptions` helper function defined in AlertsHandler.  I found it easier to have them both work the same.  If you strongly prefer that to be different, let me know.

### CODE REVIEW

**Comment by chrisnorwood** [comment]
Any thoughts/concerns/changes needed here?

**Comment by bwreid** [comment]
Apologies for our slow response on this @chrisnorwood, and that you've had to solve merge request issues consistently. On the whole, this looks great. It is a much better flow for admin.

My only suggestion would be to change the `CampaignAlerts` file to be an ES6 `class` if you're comfortable doing so. We are slowly making these changes in the rest of the codebase.

**Comment by chrisnorwood** [comment]
No worries, @bwreid .  Yes, I can absolutely do that for both CampaignAlerts and AdminAlerts actually.

The couple merge conflicts here I resolved with the Github GUI, because on my last PR I tried to do it locally, but ended up muddying up the PR with dozens of other people's commits (if that makes sense?).

If I `git pull` my local branch, thus fast forwarding it by the 55 commits or w/e, do you have any tips on how to avoid those 55 commits showing up here in this PR?  Do I have to squash them or something?  Sorry for the sort of lame question lol, but I'm kind of new to this, and I don't wanna mess it up again.

**Comment by bwreid** [comment]
Hey @chrisnorwood . Sorry about the git troubles! Instead of merging, you could likely rebase.

If you want to fix the changes locally, I think the easiest thing to do would be to likely delete your local branch (assuming you have no new commits on there) and then just re-pull this branch.

**Comment by chrisnorwood** [comment]
Excellent suggestion, thanks for the insight. I'll hop on that this evening and force push the new changes with the ES6 classes!

**Comment by chrisnorwood** [comment]
Thanks for the tips @bwreid, that worked great.

**Comment by bwreid** [comment]
@ragesoss Any additional comments you have on this?

**Comment by ragesoss** [comment]
No problems jump out in the code. I'm planning to try it out locally today as a final check.

**Comment by ragesoss** [comment]
The unchosen types in the filter select are listed multiple times (if there are multiple instances of that type).

Looks like this affects both the admin list and the campaign list.

multiple filter option repeats

**Comment by chrisnorwood** [comment]
Oof, my bad for overlooking that.  I'll fix that now.

**Comment by ragesoss** [comment]
LGTM!

**Pull request merged**
