### PR TITLE
Confirm selecting an assigned article

### LINKED ISSUE #912: Selecting an assigned article should involve a message indicating that it was selected successfully
It's currently a very subtle change as the article moves from Available to Assigned, and a user may not noticed that they succeeded.

### PR DESCRIPTION
**Pull request by arreche**
fixes #912

### CODE REVIEW

**Comment by ragesoss** [comment]
Is this ready for review and merge, or are you still working on it?

**Comment by patmbolger** [comment]
Ready for review

Patrick Bolger
774-217-4441

**Comment by arreche** [comment]
@ragesoss I have done. Now it is ready to review :)

New commits appeared because I rebased this branch with master as it is specified in [Pull request checklist](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md)

**Comment by ragesoss** [comment]
Very nice. I realized reviewing the test that there's a bug in that component: the Select button should only show up if the user is a student in the course. I'll fix that shortly.

**Pull request merged**
