### PR TITLE
Fix language names and duplicated zh

### PR DESCRIPTION
**Pull request by winstonsung**
Bug: #5627

* Fix language names\
  Change-Id: I31b6842d48b5d14cd95043b8b597dbd76a95de66
* Remove duplicated zh-hans, zh-hant\
  Change-Id: I914a4494d28bc861d21835b9cd6667e4e0937e26

## What this PR does

This PR resolves issue #5627

## Reason

* translatewiki actually export zh-CN and zh-TW by using the YAML config file.\
  https://gerrit.wikimedia.org/g/translatewiki/+/e2a5459/groups/Wikimedia/WikiEduDashboard.yaml#14
* They got added back:\
  https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/2279004
* There are incorrect and missing language names autonyms and translations

### CODE REVIEW

**Comment by ragesoss** [comment]
Thank you!

**Comment by winstonsung** [comment]
(rebased)

**Comment by winstonsung** [comment]
(previous CI result: https://github.com/WikiEducationFoundation/WikiEduDashboard/actions/runs/8084938342/job/22091901425?pr=5684 )

**Comment by ragesoss** [comment]
Looks like the specs in `application_controller_spec.rb` that are testing for zh-hans and zh-hant locales are broken.

**Comment by ragesoss** [comment]
That failure is unrelated.

**Comment by winstonsung** [comment]
(rebased)

**Comment by winstonsung** [comment]
> ```
> Offenses:
> 
> spec/features/article_viewer_spec.rb:24:101: C: Layout/LineLength: Line is too long. [118/100]
>     within(:css, '.article-viewer-legend.user-legend-name.user-highlight-1', wait: 20) do # once authorship date loads
>                                                                                                     ^^^^^^^^^^^^^^^^^^
> ```

Bruh.

**Comment by winstonsung** [comment]
Finally passed:

https://github.com/winstonsung/WikiEduDashboard/actions/runs/8092196645

**Comment by winstonsung** [comment]
(rebased)

**Comment by winstonsung** [comment]
Success:

https://github.com/winstonsung/WikiEduDashboard/actions/runs/8096291153

**Pull request merged**
