### PR TITLE
Fixes #2350 added strip course params in set_slug

### LINKED ISSUE #2350: Courses can be created with a space at the end
[This](https://outreachdashboard.wmflabs.org/courses/Wikimedia_ZA/Afrikaans_Writing_Competition) course was initially created with an additional space at the end of the title, which meant the URL ended with an additional _. I've since renamed it, but presumably additional whitespace should be trimmed before course creation.

### PR DESCRIPTION
**Pull request by garry329**
I have the striped the various the params which make up the slug on course creation.This is my first contribution to this project.Please point any mistakes or points I didn't notice.

### CODE REVIEW

**Comment by ragesoss** [comment]
@garry329 were you able to replicate the bug? This is something that already has some client-side sanitization going on, and I'm not quite sure where the trailing underscore slips through that.

**Comment by garry329** [comment]
Yes @ragesoss, I was able to replicate the bug by adding a single space after course title or institute name in the course creation form.

**Comment by ragesoss** [comment]
Thanks! This would benefit from a test, ideally a feature spec that fills out the course creation form with trailing spaces and verifying that the created course has a proper slug without the extra spaces. That way we can make sure it doesn't get re-broken later on.

**Comment by ragesoss** [comment]
I'll go ahead and merge this now.

**Pull request merged**
